#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Sinh chủ đề mới 'Thành ngữ & Tiếng lóng' (idioms_slang) cho kho câu giao tiếp, id 1001-1100."""
import json, os

ROOT = os.path.dirname(os.path.abspath(__file__))
CAT = "idioms_slang"

ITEMS = [
("Вешать лапшу на уши", "VYE-shat' lap-SHU na U-shi",
 "Nói dối, bịa chuyện để lừa ai đó (nghĩa đen: 'treo mì lên tai')",
 "Dùng khi nghi ai đó đang nói dối/bịa chuyện; khẩu ngữ, khá thân mật."),
("Бить баклуши", "BIT' bak-LU-shi",
 "Chơi không, lười biếng, không làm gì cả",
 "Ý chê trách ai đó ăn không ngồi rồi, không chịu làm việc."),
("Как две капли воды", "kak DVYE KAP-li va-DY",
 "Giống nhau như đúc, giống hệt nhau (như hai giọt nước)",
 "Dùng khi so sánh hai người/vật rất giống nhau, ví dụ anh em song sinh."),
("Делать из мухи слона", "DYE-lat' iz MU-khi sla-NA",
 "Bé xé ra to, thổi phồng chuyện nhỏ thành to",
 "Nói khi ai đó phản ứng thái quá với một việc rất nhỏ."),
("Ни пуха ни пера", "ni PU-kha ni pye-RA",
 "Chúc may mắn! (trước một việc quan trọng như thi cử, phỏng vấn)",
 "Cách chúc may mắn đặc trưng của Nga; theo phong tục phải đáp lại bằng 'К чёрту!', không nói cảm ơn."),
("К чёрту!", "k CHYOR-tu",
 "(Câu đáp lại lời chúc 'Ни пуха ни пера') để quỷ tha ma bắt / kệ nó",
 "Chỉ dùng để đáp lại câu chúc 'Ни пуха ни пера' — nghe hơi thô nhưng là quy ước văn hoá bình thường, không phải chửi thật."),
("Душа в пятки ушла", "du-SHA v PYAT-ki u-SHLA",
 "Sợ hết hồn, hồn bay phách lạc (nghĩa đen: hồn tụt xuống gót chân)",
 "Dùng khi kể lại một khoảnh khắc rất sợ hãi hoặc giật mình."),
("Заморить червячка", "za-ma-RIT' cher-vyach-KA",
 "Ăn nhẹ lót dạ một chút",
 "Dùng khi rủ ai đó ăn nhẹ trước bữa chính, thân mật đời thường."),
("Руки не доходят", "RU-ki nye da-KHO-dyat",
 "Chưa rảnh tay để làm việc gì đó (cứ bị trì hoãn vì bận)",
 "Dùng khi giải thích lý do trì hoãn một việc vì quá bận rộn."),
("Держать язык за зубами", "dyer-ZHAT' ya-ZYK za zu-BA-mi",
 "Giữ mồm giữ miệng, im lặng không tiết lộ",
 "Dùng khi dặn ai đó giữ bí mật, đừng nói ra ngoài."),
("Строить глазки", "STRO-it' GLAZ-ki",
 "Đưa mắt tình tứ, tán tỉnh bằng ánh mắt",
 "Thường dùng đùa vui khi thấy ai đó đang flirt với người khác."),
("Пускать пыль в глаза", "pus-KAT' PYL' v gla-ZA",
 "Phô trương, làm màu để gây ấn tượng giả tạo",
 "Nói về người thích khoe mẽ, phô trương hình thức hơn thực chất."),
("Съесть собаку на этом", "s'YEST' sa-BA-ku na E-tam",
 "Rất sành sỏi, dày dạn kinh nghiệm về việc gì đó",
 "Khen ai đó rất giỏi một lĩnh vực, ví dụ 'Он собаку съел на переговорах' = anh ấy rất sành đàm phán."),
("Белая ворона", "BYE-la-ya va-RO-na",
 "Người khác biệt, lập dị so với số đông (nghĩa đen: quạ trắng)",
 "Dùng để chỉ người nổi bật/khác biệt, có thể mang nghĩa tích cực hoặc tiêu cực tùy ngữ cảnh."),
("Витать в облаках", "vi-TAT' v ab-la-KAKH",
 "Đầu óc trên mây, mơ mộng viển vông, thiếu thực tế",
 "Nói về người hay mơ mộng, không chú tâm vào thực tại."),
("Водить за нос", "va-DIT' za NOS",
 "Dắt mũi, lừa gạt ai đó liên tục",
 "Dùng khi ai đó bị lừa dối/lợi dụng nhiều lần."),
("На седьмом небе от счастья", "na sed'-MOM NYE-bye at SHCHAS-tya",
 "Vui sướng tột đỉnh, hạnh phúc như trên mây",
 "Diễn tả cảm giác cực kỳ hạnh phúc, sung sướng."),
("Как рыба в воде", "kak RY-ba v va-DYE",
 "Như cá gặp nước — cảm thấy rất thoải mái, tự tin",
 "Khen ai đó cảm thấy hoàn toàn thoải mái trong một môi trường/tình huống."),
("Не в своей тарелке", "nye v sva-YEY ta-RYEL-kye",
 "Cảm thấy không thoải mái, lạc lõng (nghĩa đen: không ở trong đĩa của mình)",
 "Diễn tả cảm giác gò bó, không tự nhiên trong một hoàn cảnh nào đó."),
("Купить кота в мешке", "ku-PIT' ka-TA v myesh-KYE",
 "Mua phải 'mèo trong bao' — mua hàng không kiểm tra kỹ, rủi ro",
 "Cảnh báo khi mua đồ mà chưa xem kỹ chất lượng trước."),
("Ставить палки в колёса", "STA-vit' PAL-ki v ka-LYO-sa",
 "Chọc gậy bánh xe — cố tình cản trở, gây khó dễ",
 "Nói về ai đó cố tình gây khó khăn cho công việc/kế hoạch của người khác."),
("Работать спустя рукава", "ra-BO-tat' spus-TYA ru-ka-VA",
 "Làm việc qua loa, cẩu thả (nghĩa đen: làm việc với tay áo thả xuống)",
 "Chê trách ai đó làm việc thiếu trách nhiệm, không cẩn thận."),
("Засучить рукава", "za-su-CHIT' ru-ka-VA",
 "Xắn tay áo lên làm — bắt đầu làm việc chăm chỉ, nghiêm túc",
 "Trái nghĩa với 'работать спустя рукава'; khen tinh thần làm việc chăm chỉ."),
("Убить двух зайцев", "u-BIT' dvukh ZAY-tsev",
 "Một công đôi việc, một mũi tên trúng hai đích",
 "Dùng khi một hành động giải quyết được đồng thời hai vấn đề."),
("Первый блин комом", "PYER-vy BLIN KO-mam",
 "Vạn sự khởi đầu nan, lần đầu làm gì cũng dễ hỏng",
 "An ủi ai đó khi lần đầu làm việc gì không thành công như mong đợi."),
("Не всё то золото, что блестит", "nye VSYO ta ZO-la-ta shto bles-TIT",
 "Không phải cái gì lấp lánh cũng là vàng",
 "Câu thành ngữ cảnh báo đừng đánh giá sự vật qua vẻ bề ngoài."),
("Тише едешь — дальше будешь", "TI-she YE-desh DAL'-she BU-desh",
 "Chậm mà chắc, dục tốc bất đạt",
 "Khuyên ai đó đừng vội vàng, cẩn thận từ từ sẽ tốt hơn về lâu dài."),
("Слово не воробей, вылетит — не поймаешь", "SLO-va nye va-ra-BYEY VY-le-tit nye pay-MA-yesh",
 "Lời nói ra như chim sổ lồng, không thể thu lại — uốn lưỡi bảy lần trước khi nói",
 "Nhắc nhở phải cẩn trọng khi phát ngôn vì lời nói không rút lại được."),
("Клёво", "KLYO-va",
 "Hay, tuyệt, ngầu (từ lóng)",
 "Từ lóng rất thông dụng trong giao tiếp thân mật, tương đương 'cool' trong tiếng Anh."),
("Крутой", "kru-TOY",
 "Ngầu, đỉnh, xịn (khen ai/cái gì đó ấn tượng)",
 "Từ lóng phổ biến, khen một người/vật/việc gì đó rất ấn tượng."),
("Классно", "KLAS-na",
 "Tuyệt quá, hay quá (thán từ lóng khen ngợi)",
 "Dùng để khen ngợi điều gì đó rất hay, khá thân mật."),
("Обалдеть", "a-bal-DYET'",
 "Sững sờ, choáng váng (vì bất ngờ/ấn tượng)",
 "Thán từ lóng diễn tả sự ngạc nhiên tột độ, dùng trong giao tiếp thân mật."),
("Прикольно", "pri-KOL'-na",
 "Hay, thú vị, vui (từ lóng rất phổ biến với giới trẻ)",
 "Dùng để khen điều gì đó thú vị/hài hước."),
("Тусоваться", "tu-sa-VAT'-sya",
 "Đi chơi, tụ tập cùng bạn bè (động từ lóng)",
 "Diễn tả việc tụ họp, đi chơi cùng nhóm bạn."),
("Тусовка", "tu-SOV-ka",
 "Buổi tụ tập, buổi tiệc cùng bạn bè (danh từ lóng)",
 "Danh từ lóng chỉ buổi tụ họp bạn bè/tiệc tùng."),
("Ботан", "ba-TAN",
 "Mọt sách, người chăm học (từ lóng, hơi trêu chọc)",
 "Từ lóng gọi người học giỏi/chăm học, có thể mang ý trêu nhẹ, tránh dùng khi mới quen."),
("Го", "go",
 "Đi thôi! (từ lóng giới trẻ, vay mượn từ tiếng Anh 'go')",
 "Từ lóng rất trẻ, dùng trong nhắn tin/trò chuyện thân mật để rủ rê ai đó."),
("Го домой", "go da-MOY",
 "Về nhà thôi (cách nói thân mật, trẻ trung)",
 "Cách nói rủ rê rất thân mật, thường dùng khi nhắn tin với bạn bè."),
("Го есть", "go YEST'",
 "Đi ăn thôi (cách nói thân mật)",
 "Cách nói rủ đi ăn rất thân mật, trẻ trung, không dùng trang trọng."),
("Чувак", "chu-VAK",
 "Anh bạn, gã kia (từ lóng thân mật gọi bạn nam)",
 "Giống 'dude' trong tiếng Anh; chỉ dùng với bạn bè thân, không dùng với người lạ/cấp trên."),
("Чувиха", "chu-VI-kha",
 "Cô nàng, 'ẻm' (từ lóng gọi con gái, khá suồng sã)",
 "Khá thân mật/suồng sã, cẩn thận khi dùng vì có thể bị coi là thiếu lịch sự với người lạ."),
("Бабки", "BAB-ki",
 "Tiền (từ lóng rất thông dụng)",
 "Tương đương cách nói 'tiền tệ' kiểu lóng trong tiếng Việt; thân mật, không dùng trang trọng."),
("Бабло", "bab-LO",
 "Tiền (từ lóng, hơi thô)",
 "Từ lóng chỉ tiền, khá thô nên tránh dùng ở nơi trang trọng hoặc với người lớn tuổi."),
("Тачка", "TACH-ka",
 "Xe hơi, 'con xế' (từ lóng)",
 "Từ lóng chỉ xe hơi, dùng trong giao tiếp đời thường thân mật."),
("Хата", "KHA-ta",
 "Nhà, căn hộ (từ lóng)",
 "Từ lóng chỉ nơi ở/căn hộ, khá phổ biến trong khẩu ngữ hàng ngày."),
("Заморочки", "za-ma-ROCH-ki",
 "Những rắc rối, phiền phức lặt vặt",
 "Dùng khi than phiền về những chuyện phiền phức nhỏ nhặt trong cuộc sống."),
("Без понятия", "byez pa-NYA-ti-ya",
 "Chịu, không biết gì cả (cách nói thân mật của 'tôi không biết')",
 "Cách trả lời thân mật khi không biết câu trả lời, hơi suồng sã, tránh dùng với cấp trên."),
("Не парься", "nye PAR'-sya",
 "Đừng lo, cứ thoải mái đi (từ lóng an ủi)",
 "Câu an ủi thân mật khi ai đó đang lo lắng, giống 'cứ chill đi' trong tiếng Việt."),
("Отвали", "at-va-LI",
 "Biến đi, đừng làm phiền nữa (khá thô)",
 "Câu khá thô lỗ, chỉ nên dùng khi rất thân hoặc đang bực mình, tránh dùng với người lạ/cấp trên."),
("Забей", "za-BYEY",
 "Thôi kệ đi, bỏ qua chuyện đó đi (từ lóng)",
 "Khuyên ai đó đừng bận tâm về việc gì nữa, khá thân mật."),
("Жесть", "ZHEST'",
 "Kinh khủng, 'dữ vậy' (thán từ diễn tả sự sốc/ấn tượng mạnh)",
 "Thán từ lóng dùng khi thấy điều gì đó gây sốc/ấn tượng mạnh, tích cực hoặc tiêu cực đều dùng được."),
("Ништяк", "nish-TYAK",
 "Ổn đấy, ngon đấy (từ lóng hơi cũ nhưng vẫn thông dụng)",
 "Từ lóng khen điều gì đó ổn/tốt, mang phong cách khá bụi bặm."),
("Труба дело", "TRU-ba DYE-la",
 "Tình hình gay go, tệ rồi",
 "Dùng khi tình huống trở nên khó khăn hoặc xấu đi bất ngờ."),
("Всё путём", "VSYO pu-TYOM",
 "Mọi thứ đều ổn cả (từ lóng)",
 "Câu trả lời thân mật khi được hỏi thăm 'thế nào rồi' — nghĩa là 'ổn cả, đừng lo'."),
("Комар носа не подточит", "ka-MAR NO-sa nye pad-TO-chit",
 "Làm hoàn hảo đến mức không ai bắt bẻ được",
 "Khen ai đó làm việc cẩn thận, tỉ mỉ, hoàn hảo không sơ hở."),
("Мамой клянусь", "MA-may klya-NUS'",
 "Thề có mẹ, thề danh dự (cách thề khá suồng sã)",
 "Cách nói khẩu ngữ để nhấn mạnh mình nói thật; khá suồng sã, không dùng trang trọng."),
("Реально", "rye-AL'-na",
 "Thật đấy, thực sự (trạng từ lóng nhấn mạnh)",
 "Dùng để nhấn mạnh tính chân thực của điều vừa nói, phổ biến trong khẩu ngữ."),
("В натуре", "v na-TU-rye",
 "Thật đấy, nghiêm túc đó (từ lóng khá thô)",
 "Có gốc từ tiếng lóng trong tù, nay dùng phổ biến hơn nhưng vẫn khá thô, nên cẩn trọng khi dùng."),
("Шарить", "SHA-rit'",
 "Rành, sành sỏi về việc gì đó (động từ lóng)",
 "Từ lóng khen ai đó hiểu biết/thành thạo một lĩnh vực, ví dụ 'Он шарит в компьютерах'."),
("Не в тему", "nye v TYE-mu",
 "Lạc đề, không hợp/không đúng lúc",
 "Dùng khi ai đó nói hoặc làm gì đó không phù hợp với ngữ cảnh hiện tại."),
("По кайфу", "pa KAY-fu",
 "Thích, khoái, làm vì thích thú",
 "Diễn tả việc làm gì đó vì thích thú, thoải mái, không bị ép buộc."),
("Кайф", "KAYF",
 "Cảm giác khoái, sướng (danh từ lóng)",
 "Danh từ lóng diễn tả cảm giác thích thú, sảng khoái."),
("Достало", "das-TA-la",
 "Chán ngấy rồi, phát mệt rồi",
 "Diễn tả sự bực bội/mệt mỏi vì một điều gì đó lặp lại nhiều lần."),
("Прикинь", "pri-KIN'",
 "Biết gì không! Tưởng tượng xem! (thán từ mở đầu câu chuyện)",
 "Dùng để mở đầu khi kể một chuyện bất ngờ/thú vị cho bạn bè nghe."),
("Блин", "BLIN",
 "Trời ơi, chết thật (thán từ nhẹ thay cho từ chửi thề)",
 "Thán từ rất phổ biến để biểu lộ bực mình/ngạc nhiên nhẹ, lịch sự hơn từ chửi thề gốc."),
("Ёлки-палки", "YOL-ki PAL-ki",
 "Trời đất ơi! (thán từ ngạc nhiên/bực mình nhẹ, khá vui tai)",
 "Thán từ hơi cũ nhưng vẫn được dùng, mang tính hài hước nhẹ nhàng."),
("Дело в шляпе", "DYE-la v SHLYA-pye",
 "Coi như xong, chắc ăn rồi",
 "Dùng khi một việc gần như chắc chắn sẽ thành công/hoàn tất."),
("Игра не стоит свеч", "ig-RA nye sta-IT svyech",
 "Không đáng công sức/lợi ích bỏ ra",
 "Dùng khi đánh giá một việc không đáng để cố gắng theo đuổi."),
("Взять себя в руки", "VZYAT' sye-BYA v RU-ki",
 "Trấn tĩnh lại, kiểm soát bản thân",
 "Khuyên ai đó bình tĩnh lại sau cú sốc hoặc hoảng loạn."),
("Море по колено", "MO-rye pa ka-LYE-na",
 "Chẳng ngán gì cả, coi trời bằng vung",
 "Thường mô tả người tự tin/liều lĩnh thái quá, đôi khi ám chỉ lúc say rượu."),
("Гнуть свою линию", "GNUT' sva-YU LI-ni-yu",
 "Khăng khăng giữ quan điểm của mình, không nhượng bộ",
 "Mô tả người kiên quyết bảo vệ ý kiến riêng trong tranh luận/đàm phán."),
("Сесть в лужу", "SYEST' v LU-zhu",
 "Bị bẽ mặt, thất bại xấu hổ trước mặt người khác",
 "Dùng khi ai đó rơi vào tình huống xấu hổ/thất bại công khai."),
("Взять быка за рога", "VZYAT' by-KA za ra-GA",
 "Nắm bắt vấn đề cốt lõi, hành động dứt khoát",
 "Khuyên ai đó xử lý vấn đề một cách trực tiếp, quyết đoán."),
("Овчинка выделки не стоит", "af-CHIN-ka VY-del-ki nye sta-IT",
 "Không bõ công, không đáng để làm",
 "Thành ngữ cổ nhưng vẫn dùng, ý nghĩa tương tự 'không đáng công sức bỏ ra'."),
("Не лезь не в своё дело", "nye LYEZ' nye v sva-YO DYE-la",
 "Đừng xen vào chuyện không phải của mình",
 "Câu nói khá thẳng, dùng khi ai đó can thiệp không đúng chỗ."),
("Моя хата с краю", "ma-YA KHA-ta s KRA-yu",
 "Chuyện đó không liên quan đến tôi (thành ngữ trốn tránh trách nhiệm)",
 "Thường dùng hơi mỉa mai khi ai đó cố tránh trách nhiệm/không muốn dính vào rắc rối."),
("Одна нога здесь, другая там", "ad-NA na-GA ZDYES' dru-GA-ya TAM",
 "Đi thật nhanh rồi quay lại ngay",
 "Dùng để giục ai đó đi làm việc gì đó thật nhanh rồi quay lại."),
("Смотреть сквозь пальцы", "smat-RYET' SKVOZ' PAL'-tsy",
 "Cố tình làm ngơ, bỏ qua lỗi của ai đó",
 "Dùng khi ai đó biết sai phạm nhưng cố tình không xử lý/nhắc nhở."),
("Выйти сухим из воды", "VY-yti su-KHIM iz va-DY",
 "Thoát khỏi rắc rối mà không hề hấn gì",
 "Mô tả người khéo léo thoát khỏi trách nhiệm/rắc rối mà không bị trừng phạt."),
("Крыша едет", "KRY-sha YE-det",
 "Phát điên, đầu óc quay cuồng (từ lóng)",
 "Từ lóng diễn tả cảm giác căng thẳng/quá tải đến mức 'muốn điên'."),
("Голова идёт кругом", "ga-la-VA i-DYOT KRU-gam",
 "Đầu óc quay cuồng, rối trí vì quá nhiều việc",
 "Diễn tả cảm giác choáng ngợp, rối trí vì quá tải công việc/thông tin."),
("Мороз по коже", "ma-ROZ pa KO-zhe",
 "Nổi da gà, rùng mình (vì sợ hãi hoặc xúc động)",
 "Diễn tả cảm giác rùng mình mạnh vì sợ hãi hoặc xúc động mạnh."),
("Сгорать со стыда", "sga-RAT' sa sty-DA",
 "Xấu hổ đến mức muốn độn thổ",
 "Diễn tả cảm giác cực kỳ xấu hổ trước một tình huống nào đó."),
("Как снег на голову", "kak SNYEG na GO-la-vu",
 "Đến bất ngờ, đột ngột không báo trước",
 "Dùng khi mô tả điều gì đó xảy ra bất ngờ, không có dấu hiệu báo trước."),
("Хлебом не корми", "KHLYE-bam nye kar-MI",
 "Rất mê, rất thích điều gì đó",
 "Ví dụ 'Его хлебом не корми, дай поиграть в футбол' = nó mê đá bóng lắm, không cần cho ăn cũng được."),
("Свои люди — сочтёмся", "SVO-i LYU-di sach-TYOM-sya",
 "Người nhà cả, tính sau cũng được",
 "Dùng thân mật giữa bạn bè/người quen khi nói về việc trả nợ/thanh toán không cần gấp gáp."),
("Не мытьём, так катаньем", "nye myt'-YOM tak ka-TAN'-yem",
 "Không cách này thì cách khác cũng phải đạt được",
 "Diễn tả sự kiên trì tìm mọi cách để đạt mục đích."),
("Обещать золотые горы", "a-bye-SHCHAT' za-la-TY-ye GO-ry",
 "Hứa hẹn viển vông, hứa suông",
 "Chỉ trích ai đó hứa hẹn quá đà nhưng không thực hiện được."),
("Тянуть кота за хвост", "tya-NUT' ka-TA za KHVOST",
 "Kéo dài lê thê, trì hoãn không cần thiết",
 "Dùng khi chê trách ai đó làm việc/nói chuyện quá chậm chạp, dây dưa."),
("Разговор по душам", "raz-ga-VOR pa du-SHAM",
 "Cuộc trò chuyện thân tình, chia sẻ chân thành",
 "Diễn tả một cuộc nói chuyện cởi mở, chân thành, thường về vấn đề tình cảm/cá nhân."),
("Держать в курсе", "dyer-ZHAT' v KUR-sye",
 "Cập nhật thông tin thường xuyên cho ai đó",
 "Rất hữu ích trong công việc, ví dụ 'Держите меня в курсе' = hãy cập nhật cho tôi biết tình hình."),
("Быть в курсе", "BYT' v KUR-sye",
 "Nắm rõ tình hình, biết thông tin mới nhất",
 "Thường dùng trong công việc khi hỏi/khẳng định ai đó có biết thông tin mới nhất không."),
("На всякий случай", "na VSYA-kiy SLU-chay",
 "Để phòng hờ, đề phòng trường hợp xấu",
 "Cụm từ rất thông dụng khi chuẩn bị một phương án dự phòng."),
("Само собой разумеется", "sa-MO sa-BOY ra-zu-MYE-yet-sya",
 "Dĩ nhiên rồi, hiển nhiên là vậy",
 "Dùng khi khẳng định điều gì đó là hiển nhiên, không cần bàn cãi thêm."),
("Это долгая история", "E-ta DOL-ga-ya is-TO-ri-ya",
 "Chuyện dài lắm, kể ra thì dài dòng",
 "Dùng khi muốn tránh giải thích chi tiết một câu chuyện phức tạp hoặc nhạy cảm."),
("Палец о палец не ударить", "PA-lyets a PA-lyets nye u-DA-rit'",
 "Không nhấc một ngón tay, hoàn toàn không làm gì cả",
 "Chê trách ai đó lười biếng, không đóng góp chút công sức nào."),
("Мухи не обидит", "MU-khi nye a-BI-dit",
 "Hiền như đất, không làm hại ai (nghĩa đen: không làm hại cả con ruồi)",
 "Khen ai đó có tính cách rất hiền lành, vô hại."),
("Кровь из носу", "KROF' iz NO-su",
 "Bằng mọi giá, dù có phải cố gắng đến kiệt sức",
 "Nhấn mạnh quyết tâm phải hoàn thành việc gì đó bằng mọi giá."),
("Заткнись", "zat-KNIS'",
 "Im miệng đi (rất thô, chỉ dùng khi rất bực)",
 "Câu mệnh lệnh rất thô lỗ, tuyệt đối tránh dùng với người lạ, cấp trên hoặc trong công việc."),
("Ёпрст", "yop-rst",
 "(thán từ lóng nhẹ nhàng thay cho từ chửi thề khi bực mình/ngạc nhiên)",
 "Thán từ vui tai, lịch sự hơn từ gốc, dùng khi giật mình hoặc hơi bực."),
("Фиолетово", "fi-a-LYE-ta-va",
 "Chẳng quan tâm, kệ luôn (từ lóng, nghĩa đen 'màu tím')",
 "Từ lóng diễn tả thái độ thờ ơ, không quan tâm đến chuyện gì đó."),
("По барабану", "pa ba-ra-BA-nu",
 "Chẳng quan tâm, kệ nó (từ lóng, nghĩa đen 'theo cái trống')",
 "Diễn tả thái độ thờ ơ, không mảy may bận tâm về điều gì đó."),
("Заколебал", "za-ka-lye-BAL",
 "Làm phát mệt, quấy rầy quá mức (khá thô)",
 "Dùng khi ai đó liên tục làm phiền đến mức khó chịu; khá thô, tránh dùng trang trọng."),
("Не гони", "nye ga-NI",
 "Đừng nói phét, đừng phóng đại (từ lóng)",
 "Dùng khi nghi ngờ ai đó đang nói quá lên hoặc bịa chuyện."),
("Гнать (пургу)", "GNAT' pur-GU",
 "Nói phét, ba hoa những điều không có thật",
 "Từ lóng chê trách ai đó đang nói dối/khoác lác."),
("В шоке", "v SHO-kye",
 "Sốc, không tin nổi (từ lóng)",
 "Diễn tả sự bất ngờ/sốc trước một tin tức hoặc sự việc nào đó."),
("Отпад", "at-PAD",
 "Tuyệt vời, đỉnh cao (từ lóng khen ngợi)",
 "Thán từ lóng khen điều gì đó cực kỳ ấn tượng, tích cực."),
("На автомате", "na af-ta-MA-tye",
 "Làm theo phản xạ, không cần suy nghĩ (như cái máy)",
 "Diễn tả việc làm gì đó theo thói quen/phản xạ mà không cần để ý."),
("Сто пудов", "sto pu-DOF",
 "Chắc chắn trăm phần trăm (từ lóng nhấn mạnh)",
 "Dùng để khẳng định điều gì đó chắc chắn xảy ra, khá thân mật."),
("Без базара", "byez ba-ZA-ra",
 "Được thôi, không vấn đề gì (từ lóng đồng ý)",
 "Cách đồng ý thân mật/suồng sã, nghĩa đen 'không cần mặc cả'."),
]

data = []
for i, (ru, phonetic, meaning, note) in enumerate(ITEMS, start=1001):
    data.append({
        "id": i, "ru": ru, "phonetic": phonetic,
        "meaning": meaning, "note": note, "category": CAT,
    })

out_path = os.path.join(ROOT, "sentences_6.json")
with open(out_path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False)
print(f"Wrote {len(data)} idiom/slang items to {out_path} (id {data[0]['id']}-{data[-1]['id']})")
