#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Patch duplicate 'ru' entries flagged by merge.py with fresh, unique, useful content.
Keeps id/category unchanged; replaces ru/phonetic/pos/meaning/usage/example fields."""
import json, os

ROOT = os.path.dirname(os.path.abspath(__file__))

WORD_PATCH = {
491: dict(ru="консьерж", phonetic="kon-si-YERZH", pos="n", meaning="nhân viên concierge (hỗ trợ khách)",
    usage="Người ở quầy khách sạn giúp đặt tour, gọi taxi, tư vấn tham quan.",
    example_ru="Консьерж поможет вам заказать такси.", example_vi="Nhân viên concierge sẽ giúp bạn gọi taxi."),
641: dict(ru="сдача", phonetic="SDA-cha", pos="n", meaning="tiền thừa",
    usage="Dùng khi thanh toán tiền mặt và nhận lại tiền thừa.",
    example_ru="Возьмите сдачу, пожалуйста.", example_vi="Xin hãy lấy tiền thừa."),
855: dict(ru="бюджет", phonetic="byu-DZHET", pos="n", meaning="ngân sách",
    usage="Dùng khi bàn về ngân sách dự án hoặc công ty trong công việc.",
    example_ru="Мы обсудим бюджет проекта завтра.", example_vi="Chúng ta sẽ bàn về ngân sách dự án vào ngày mai."),
526: dict(ru="полотенце", phonetic="pa-la-TYEN-tse", pos="n", meaning="khăn tắm",
    usage="Dùng khi xin thêm khăn tắm ở khách sạn.",
    example_ru="Можно ещё одно полотенце?", example_vi="Cho tôi xin thêm một chiếc khăn tắm được không?"),
527: dict(ru="постельное бельё", phonetic="pas-TYEL-na-ye byel-YO", pos="phrase", meaning="bộ ga giường, chăn ga gối",
    usage="Dùng khi yêu cầu lễ tân thay ga giường mới.",
    example_ru="Пожалуйста, поменяйте постельное бельё.", example_vi="Làm ơn thay bộ ga giường mới giúp tôi."),
895: dict(ru="переговоры", phonetic="pe-re-ga-VO-ry", pos="n", meaning="đàm phán",
    usage="Dùng khi nói về buổi đàm phán kinh doanh giữa các bên.",
    example_ru="Переговоры прошли успешно.", example_vi="Buổi đàm phán đã diễn ra thành công."),
896: dict(ru="отчёт", phonetic="at-CHYOT", pos="n", meaning="báo cáo",
    usage="Dùng khi nộp báo cáo công việc cho cấp trên hoặc đối tác.",
    example_ru="Мне нужно подготовить отчёт к пятнице.", example_vi="Tôi cần chuẩn bị báo cáo trước thứ Sáu."),
696: dict(ru="тележка", phonetic="te-LYEZH-ka", pos="n", meaning="xe đẩy hành lý",
    usage="Dùng ở sân bay/siêu thị để đẩy hành lý hoặc hàng hóa.",
    example_ru="Где можно взять тележку для багажа?", example_vi="Tôi có thể lấy xe đẩy hành lý ở đâu?"),
489: dict(ru="администратор", phonetic="ad-mi-nis-TRA-tar", pos="n", meaning="lễ tân/quản lý ca trực khách sạn",
    usage="Người phụ trách quầy lễ tân, xử lý các vấn đề phòng ốc.",
    example_ru="Обратитесь к администратору на ресепшене.", example_vi="Hãy hỏi lễ tân ở quầy tiếp tân."),
672: dict(ru="декларация", phonetic="dek-la-RA-tsi-ya", pos="n", meaning="tờ khai hải quan",
    usage="Điền tờ khai này khi mang hàng hóa/tiền vượt mức quy định qua hải quan.",
    example_ru="Заполните таможенную декларацию.", example_vi="Hãy điền tờ khai hải quan."),
618: dict(ru="квитанция", phonetic="kvi-TAN-tsi-ya", pos="n", meaning="biên lai",
    usage="Giữ lại biên lai để đổi trả hàng hoặc làm bằng chứng thanh toán.",
    example_ru="Сохраните квитанцию на случай возврата.", example_vi="Hãy giữ lại biên lai phòng khi cần đổi trả."),
673: dict(ru="миграционная карта", phonetic="mig-ra-tsi-ON-na-ya KAR-ta", pos="phrase", meaning="thẻ nhập cảnh (tờ khai di trú)",
    usage="Điền khi nhập cảnh Nga, phải giữ lại đến khi xuất cảnh.",
    example_ru="Не теряйте миграционную карту.", example_vi="Đừng làm mất thẻ nhập cảnh."),
913: dict(ru="командировочные", phonetic="ka-man-di-ROV-ach-ny-ye", pos="n", meaning="phụ cấp công tác",
    usage="Khoản tiền công ty chi trả cho nhân viên đi công tác.",
    example_ru="Командировочные выплачиваются заранее.", example_vi="Phụ cấp công tác được trả trước."),
403: dict(ru="проездной", phonetic="pra-yez-NOY", pos="n", meaning="vé tháng/thẻ đi lại",
    usage="Dùng thẻ vé tháng cho phương tiện công cộng thay vì mua vé lẻ.",
    example_ru="Я купил проездной на месяц.", example_vi="Tôi đã mua vé tháng đi lại."),
671: dict(ru="терминал", phonetic="ter-mi-NAL", pos="n", meaning="nhà ga (sân bay)",
    usage="Hỏi terminal nào để đến đúng khu vực check-in.",
    example_ru="Из какого терминала вылетает рейс?", example_vi="Chuyến bay khởi hành từ nhà ga nào?"),
684: dict(ru="иллюминатор", phonetic="il-lyu-mi-NA-tar", pos="n", meaning="cửa sổ máy bay",
    usage="Dùng khi xin chỗ ngồi cạnh cửa sổ máy bay.",
    example_ru="Я хочу место у иллюминатора.", example_vi="Tôi muốn ngồi cạnh cửa sổ máy bay."),
685: dict(ru="экипаж", phonetic="e-ki-PAZH", pos="n", meaning="phi hành đoàn",
    usage="Chỉ toàn bộ tổ bay gồm phi công và tiếp viên.",
    example_ru="Экипаж приветствует пассажиров на борту.", example_vi="Phi hành đoàn chào đón hành khách lên máy bay."),
686: dict(ru="аварийный выход", phonetic="a-va-RIY-ny VY-khad", pos="phrase", meaning="cửa thoát hiểm",
    usage="Vị trí cửa thoát hiểm trên máy bay hoặc tòa nhà.",
    example_ru="Аварийный выход находится справа.", example_vi="Cửa thoát hiểm nằm ở bên phải."),
687: dict(ru="ремень безопасности", phonetic="re-MYEN' bez-a-PAS-nas-ti", pos="phrase", meaning="dây an toàn",
    usage="Yêu cầu thắt dây an toàn khi máy bay cất/hạ cánh.",
    example_ru="Пристегните ремень безопасности.", example_vi="Hãy thắt dây an toàn."),
712: dict(ru="выход на посадку", phonetic="VY-khad na pa-SAD-ku", pos="phrase", meaning="cổng lên máy bay",
    usage="Kiểm tra bảng thông tin để biết cổng lên máy bay của mình.",
    example_ru="Наш выход на посадку номер двенадцать.", example_vi="Cổng lên máy bay của chúng ta là số 12."),
678: dict(ru="стойка регистрации", phonetic="STOY-ka re-gis-TRA-tsi-i", pos="phrase", meaning="quầy làm thủ tục check-in",
    usage="Đến quầy này để nhận thẻ lên máy bay và gửi hành lý.",
    example_ru="Стойка регистрации закрывается за сорок минут до вылета.", example_vi="Quầy check-in đóng cửa trước giờ bay 40 phút."),
689: dict(ru="зона вылета", phonetic="ZO-na VY-le-ta", pos="phrase", meaning="khu vực chờ ra máy bay (sau an ninh)",
    usage="Khu vực sau khi qua an ninh, chờ đến giờ lên máy bay.",
    example_ru="В зоне вылета есть кафе и магазины.", example_vi="Ở khu vực chờ ra máy bay có quán cà phê và cửa hàng."),
674: dict(ru="декларировать", phonetic="dek-la-RI-ra-vat'", pos="v", meaning="khai báo (hải quan)",
    usage="Dùng khi khai báo hàng hóa/tiền mang theo lúc qua hải quan.",
    example_ru="Вам нужно декларировать эту сумму?", example_vi="Bạn có cần khai báo số tiền này không?"),
675: dict(ru="лишний вес", phonetic="LISH-niy VYES", pos="phrase", meaning="hành lý quá cân",
    usage="Khi hành lý vượt cân quy định, phải trả thêm phí.",
    example_ru="У вас лишний вес багажа, придётся доплатить.", example_vi="Hành lý của bạn quá cân, bạn cần trả thêm phí."),
676: dict(ru="получение багажа", phonetic="pa-lu-CHE-ni-ye ba-ga-ZHA", pos="phrase", meaning="khu vực nhận hành lý",
    usage="Nơi lấy vali sau khi máy bay hạ cánh.",
    example_ru="Где находится получение багажа?", example_vi="Khu vực nhận hành lý ở đâu?"),
695: dict(ru="бирка", phonetic="BIR-ka", pos="n", meaning="thẻ hành lý",
    usage="Dán thẻ tên lên vali để dễ nhận diện.",
    example_ru="Прикрепите бирку к чемодану.", example_vi="Hãy gắn thẻ tên vào vali."),
679: dict(ru="стыковочный рейс", phonetic="sty-KO-vach-niy REYS", pos="phrase", meaning="chuyến bay nối chuyến",
    usage="Dùng khi phải đổi máy bay giữa hành trình.",
    example_ru="У меня стыковочный рейс через два часа.", example_vi="Tôi có chuyến bay nối chuyến sau hai tiếng nữa."),
710: dict(ru="объявление", phonetic="ab-yav-LYE-ni-ye", pos="n", meaning="thông báo (loa phát thanh)",
    usage="Nghe thông báo qua loa ở sân bay/ga tàu.",
    example_ru="По громкой связи было объявление о задержке.", example_vi="Có thông báo qua loa về việc trễ chuyến."),
711: dict(ru="негабаритный багаж", phonetic="ne-ga-ba-RIT-niy ba-GAZH", pos="phrase", meaning="hành lý cồng kềnh/quá khổ",
    usage="Hành lý như vali cỡ lớn, xe đẩy trẻ em... cần gửi ở khu riêng.",
    example_ru="Негабаритный багаж сдают в отдельной зоне.", example_vi="Hành lý quá khổ được gửi ở khu vực riêng."),
709: dict(ru="транзитная зона", phonetic="tran-ZIT-na-ya ZO-na", pos="phrase", meaning="khu vực quá cảnh",
    usage="Khu vực dành cho khách quá cảnh không cần nhập cảnh.",
    example_ru="Мы ждём в транзитной зоне.", example_vi="Chúng tôi đang chờ ở khu vực quá cảnh."),
609: dict(ru="чек", phonetic="CHEK", pos="n", meaning="hóa đơn (giấy) khi mua hàng",
    usage="Giữ hóa đơn mua hàng để đổi trả nếu cần.",
    example_ru="Не забудьте чек.", example_vi="Đừng quên lấy hóa đơn."),
778: dict(ru="рецепт", phonetic="re-TSEPT", pos="n", meaning="đơn thuốc",
    usage="Cần đơn thuốc của bác sĩ để mua một số loại thuốc.",
    example_ru="Это лекарство продаётся только по рецепту.", example_vi="Thuốc này chỉ bán khi có đơn thuốc."),
627: dict(ru="наличными", phonetic="na-LICH-ny-mi", pos="adv", meaning="bằng tiền mặt",
    usage="Trả lời khi được hỏi thanh toán bằng hình thức gì.",
    example_ru="Я заплачу наличными.", example_vi="Tôi sẽ trả bằng tiền mặt."),
856: dict(ru="предоплата", phonetic="pre-da-PLA-ta", pos="n", meaning="tiền đặt cọc, trả trước",
    usage="Yêu cầu đặt cọc trước khi ký hợp đồng hoặc đặt dịch vụ.",
    example_ru="Требуется предоплата пятьдесят процентов.", example_vi="Cần đặt cọc trước 50 phần trăm."),
656: dict(ru="примерочная", phonetic="pri-MYE-rach-na-ya", pos="n", meaning="phòng thử đồ",
    usage="Hỏi phòng thử đồ ở đâu khi mua quần áo.",
    example_ru="Где находится примерочная?", example_vi="Phòng thử đồ ở đâu ạ?"),
640: dict(ru="распродажа", phonetic="ras-pra-DA-zha", pos="n", meaning="đợt giảm giá, xả hàng",
    usage="Dùng khi cửa hàng có chương trình giảm giá lớn.",
    example_ru="В магазине сейчас распродажа.", example_vi="Cửa hàng đang có đợt giảm giá."),
603: dict(ru="витрина", phonetic="vit-RI-na", pos="n", meaning="tủ kính trưng bày",
    usage="Nhìn hàng trưng bày trong tủ kính cửa hàng.",
    example_ru="Это платье было на витрине.", example_vi="Chiếc váy này được trưng bày ở tủ kính."),
920: dict(ru="конкурент", phonetic="kan-ku-RENT", pos="n", meaning="đối thủ cạnh tranh",
    usage="Nói về công ty đối thủ trên thị trường.",
    example_ru="Наш главный конкурент снизил цены.", example_vi="Đối thủ cạnh tranh chính của chúng tôi đã giảm giá."),
654: dict(ru="прилавок", phonetic="pri-LA-vak", pos="n", meaning="quầy hàng",
    usage="Quầy trưng bày hàng hóa trong cửa hàng/chợ.",
    example_ru="Товар лежит на прилавке.", example_vi="Hàng hóa được bày trên quầy."),
602: dict(ru="продуктовый магазин", phonetic="prad-uk-TO-vy ma-ga-ZIN", pos="phrase", meaning="cửa hàng tạp hóa/thực phẩm",
    usage="Cửa hàng nhỏ bán đồ ăn hàng ngày, khác với siêu thị lớn.",
    example_ru="Рядом есть продуктовый магазин.", example_vi="Gần đây có một cửa hàng tạp hóa."),
767: dict(ru="укол", phonetic="u-KOL", pos="n", meaning="mũi tiêm",
    usage="Dùng khi nói về việc tiêm thuốc tại bệnh viện/phòng khám.",
    example_ru="Мне нужно сделать укол.", example_vi="Tôi cần tiêm một mũi."),
619: dict(ru="терминал оплаты", phonetic="ter-mi-NAL ap-LA-ty", pos="phrase", meaning="máy quẹt thẻ thanh toán (POS)",
    usage="Dùng khi thanh toán bằng thẻ tại quầy thu ngân.",
    example_ru="Проведите карту через терминал оплаты.", example_vi="Hãy quẹt thẻ qua máy thanh toán."),
889: dict(ru="издержки", phonetic="iz-DYERZH-ki", pos="n", meaning="chi phí",
    usage="Nói về các chi phí phát sinh trong kinh doanh.",
    example_ru="Нужно сократить издержки.", example_vi="Cần cắt giảm chi phí."),
888: dict(ru="прибыль", phonetic="PRI-byl'", pos="n", meaning="lợi nhuận",
    usage="Nói về lợi nhuận công ty thu được.",
    example_ru="В этом году прибыль выросла.", example_vi="Năm nay lợi nhuận đã tăng."),
890: dict(ru="печать", phonetic="pe-CHAT'", pos="n", meaning="con dấu công ty",
    usage="Đóng dấu lên hợp đồng/giấy tờ để xác nhận.",
    example_ru="Поставьте печать компании здесь.", example_vi="Hãy đóng dấu công ty vào đây."),
803: dict(ru="прогноз погоды", phonetic="prag-NOZ pa-GO-dy", pos="phrase", meaning="dự báo thời tiết",
    usage="Xem dự báo thời tiết trước khi ra ngoài hoặc đi công tác.",
    example_ru="Ты смотрел прогноз погоды на завтра?", example_vi="Bạn đã xem dự báo thời tiết ngày mai chưa?"),
984: dict(ru="уставший", phonetic="us-TAV-shiy", pos="adj", meaning="mệt mỏi",
    usage="Diễn tả trạng thái mệt sau khi làm việc/di chuyển nhiều.",
    example_ru="Я очень уставший после перелёта.", example_vi="Tôi rất mệt sau chuyến bay."),
985: dict(ru="уверенный", phonetic="u-VYE-ren-niy", pos="adj", meaning="tự tin",
    usage="Diễn tả sự tự tin khi nói chuyện hoặc đàm phán.",
    example_ru="Он выглядит очень уверенным на переговорах.", example_vi="Anh ấy trông rất tự tin khi đàm phán."),
630: dict(ru="торговаться", phonetic="tar-ga-VAT'-sya", pos="v", meaning="mặc cả, trả giá",
    usage="Dùng ở chợ hoặc cửa hàng nhỏ, có thể mặc cả giá.",
    example_ru="На рынке можно торговаться.", example_vi="Ở chợ có thể mặc cả giá được."),
762: dict(ru="терапевт", phonetic="te-ra-PEVT", pos="n", meaning="bác sĩ đa khoa",
    usage="Bác sĩ khám tổng quát đầu tiên trước khi chuyển chuyên khoa.",
    example_ru="Сначала нужно записаться к терапевту.", example_vi="Trước tiên bạn cần đặt lịch khám với bác sĩ đa khoa."),
871: dict(ru="генеральный директор", phonetic="ge-ne-RAL'-niy di-REK-tar", pos="phrase", meaning="tổng giám đốc",
    usage="Chức danh người đứng đầu công ty.",
    example_ru="Генеральный директор подпишет договор лично.", example_vi="Tổng giám đốc sẽ trực tiếp ký hợp đồng."),
915: dict(ru="стажёр", phonetic="sta-ZHYOR", pos="n", meaning="thực tập sinh",
    usage="Nhân viên đang thực tập tại công ty.",
    example_ru="У нас работает несколько стажёров.", example_vi="Công ty chúng tôi có vài thực tập sinh."),
417: dict(ru="пробка", phonetic="PROB-ka", pos="n", meaning="tắc đường, kẹt xe",
    usage="Dùng khi đường đông xe cộ không di chuyển được.",
    example_ru="На дороге большая пробка.", example_vi="Đường đang bị tắc nghiêm trọng."),
612: dict(ru="кассир", phonetic="ka-SIR", pos="n", meaning="thu ngân",
    usage="Người thu tiền tại quầy thanh toán.",
    example_ru="Кассир выдаст вам чек.", example_vi="Thu ngân sẽ đưa hóa đơn cho bạn."),
859: dict(ru="заместитель", phonetic="za-mes-TI-tel'", pos="n", meaning="phó (giám đốc/trưởng phòng)",
    usage="Chức danh cấp phó trong công ty.",
    example_ru="Заместитель директора проведёт встречу.", example_vi="Phó giám đốc sẽ chủ trì buổi họp."),
872: dict(ru="подрядчик", phonetic="pad-RYAD-chik", pos="n", meaning="nhà thầu",
    usage="Công ty/cá nhân thực hiện hợp đồng thầu.",
    example_ru="Мы наняли нового подрядчика.", example_vi="Chúng tôi đã thuê một nhà thầu mới."),
870: dict(ru="поставщик", phonetic="pas-tav-SHCHIK", pos="n", meaning="nhà cung cấp",
    usage="Công ty cung cấp hàng hóa/dịch vụ cho doanh nghiệp khác.",
    example_ru="Мы работаем с этим поставщиком пять лет.", example_vi="Chúng tôi hợp tác với nhà cung cấp này được năm năm."),
941: dict(ru="спокойный", phonetic="spa-KOY-niy", pos="adj", meaning="bình tĩnh, điềm tĩnh",
    usage="Diễn tả trạng thái bình tĩnh, không hoảng loạn.",
    example_ru="Он всегда спокойный, даже в стрессе.", example_vi="Anh ấy luôn bình tĩnh, kể cả khi căng thẳng."),
944: dict(ru="внимательный", phonetic="vni-MA-tel'-niy", pos="adj", meaning="chu đáo, cẩn thận",
    usage="Khen ai đó chu đáo, tỉ mỉ với từng chi tiết.",
    example_ru="Она очень внимательная к деталям.", example_vi="Cô ấy rất chu đáo với từng chi tiết."),
946: dict(ru="щедрый", phonetic="SHCHED-ryi", pos="adj", meaning="hào phóng, rộng rãi",
    usage="Khen ai đó hào phóng, rộng lượng.",
    example_ru="Спасибо, вы очень щедрый человек.", example_vi="Cảm ơn, anh thật là người hào phóng."),
990: dict(ru="терпеливый", phonetic="ter-pe-LI-vyi", pos="adj", meaning="kiên nhẫn",
    usage="Khen ai đó kiên nhẫn, không nóng vội.",
    example_ru="Врач был очень терпеливым с пациентом.", example_vi="Bác sĩ rất kiên nhẫn với bệnh nhân."),
863: dict(ru="инвестор", phonetic="in-VYES-tar", pos="n", meaning="nhà đầu tư",
    usage="Người/tổ chức rót vốn đầu tư vào công ty.",
    example_ru="Мы ищем нового инвестора.", example_vi="Chúng tôi đang tìm nhà đầu tư mới."),
}

SENT_PATCH = {
427: dict(ru="Можно ли заселиться раньше, чем в стандартное время?",
    phonetic="MOZH-na li za-se-LIT'-sya RAN'-she chem v stan-DART-na-ye VRE-mya?",
    meaning="Tôi có thể nhận phòng sớm hơn giờ quy định không?",
    note="Hỏi lễ tân khách sạn khi muốn check-in sớm hơn bình thường."),
800: dict(ru="Этот автобус идёт до центра города?",
    phonetic="E-tat af-TO-bus i-DYOT da TSENT-ra GO-ra-da?",
    meaning="Xe buýt này có đến trung tâm thành phố không?",
    note="Hỏi tài xế hoặc hành khách khác khi lên xe buýt."),
981: dict(ru="Мы готовы подписать договор сегодня.",
    phonetic="My ga-TO-vy pad-pi-SAT' da-ga-VOR se-VOD-nya.",
    meaning="Chúng tôi sẵn sàng ký hợp đồng hôm nay.",
    note="Dùng khi đàm phán đi đến kết quả cuối cùng, sẵn sàng ký kết."),
611: dict(ru="Можно расплатиться картой?",
    phonetic="MOZH-na ras-pla-TIT'-sya KAR-tay?",
    meaning="Tôi có thể thanh toán bằng thẻ được không?",
    note="Hỏi khi muốn trả bằng thẻ ngân hàng thay vì tiền mặt."),
678: dict(ru="У вас есть эта модель в другом цвете?",
    phonetic="U vas yest' E-ta ma-DEL' v dru-GOM TSVYE-tye?",
    meaning="Cửa hàng có mẫu này màu khác không?",
    note="Hỏi khi muốn đổi màu sản phẩm lúc mua sắm."),
658: dict(ru="Можно вернуть этот товар без чека?",
    phonetic="MOZH-na ver-NUT' E-tat ta-VAR bez CHE-ka?",
    meaning="Tôi có thể trả lại món hàng này mà không có hóa đơn không?",
    note="Hỏi khi muốn đổi/trả hàng nhưng không giữ hóa đơn."),
}

def patch_kind(kind, patch, id_to_chunk):
    changed_files = set()
    for iid, fields in patch.items():
        chunk = id_to_chunk(iid)
        path = os.path.join(ROOT, chunk)
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        found = False
        for it in data:
            if it["id"] == iid:
                for k, v in fields.items():
                    it[k] = v
                found = True
                break
        if not found:
            raise SystemExit(f"id {iid} not found in {chunk}")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=None)
        changed_files.add(chunk)
    print(f"{kind}: patched {len(patch)} ids across files {sorted(changed_files)}")

def word_chunk(iid):
    idx = (iid - 1) // 200 + 1
    return f"words_{idx}.json"

def sent_chunk(iid):
    idx = (iid - 1) // 200 + 1
    return f"sentences_{idx}.json"

patch_kind("words", WORD_PATCH, word_chunk)
patch_kind("sentences", SENT_PATCH, sent_chunk)
print("Done.")
