#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Round 1: thay các mục 'ru' bị trùng trong gói tiếng Trung, giữ nguyên id/category."""
import json, os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "zh")

WORD_PATCH = {
346: dict(ru="调料", phonetic="tiáo liào", pos="n", meaning="gia vị",
    usage="Gia vị nói chung dùng khi nấu ăn.",
    example_ru="这道菜需要更多调料。", example_vi="Món này cần thêm gia vị."),
427: dict(ru="候机", phonetic="hòu jī", pos="v", meaning="chờ lên máy bay (tại phòng chờ)",
    usage="Hành động chờ đợi tại khu vực chờ bay.",
    example_ru="我们在候机厅候机。", example_vi="Chúng tôi đang chờ bay ở phòng chờ."),
428: dict(ru="抵达", phonetic="dǐ dá", pos="v", meaning="đến nơi (trang trọng hơn 到达)",
    usage="Dùng trong ngữ cảnh trang trọng/thông báo, đồng nghĩa 到达.",
    example_ru="航班将于下午三点抵达。", example_vi="Chuyến bay sẽ đến nơi lúc 3 giờ chiều."),
453: dict(ru="乘务员", phonetic="chéng wù yuán", pos="n", meaning="nhân viên phục vụ trên tàu/xe (tiếp viên)",
    usage="Nhân viên phục vụ hành khách trên tàu hỏa/xe buýt.",
    example_ru="请问乘务员在哪里？", example_vi="Xin hỏi nhân viên phục vụ ở đâu?"),
479: dict(ru="礼宾部", phonetic="lǐ bīn bù", pos="n", meaning="bộ phận concierge/hỗ trợ khách sạn",
    usage="Bộ phận hỗ trợ đặt tour, gọi taxi tại khách sạn.",
    example_ru="您可以问礼宾部。", example_vi="Bạn có thể hỏi bộ phận concierge."),
480: dict(ru="续住", phonetic="xù zhù", pos="v", meaning="gia hạn lưu trú",
    usage="Gia hạn thêm thời gian ở khách sạn.",
    example_ru="我想续住一晚。", example_vi="Tôi muốn gia hạn ở thêm một đêm."),
486: dict(ru="浴袍", phonetic="yù páo", pos="n", meaning="áo choàng tắm",
    usage="Đồ dùng trong phòng khách sạn để mặc sau khi tắm.",
    example_ru="衣柜里有浴袍。", example_vi="Trong tủ có áo choàng tắm."),
492: dict(ru="拖鞋", phonetic="tuō xié", pos="n", meaning="dép đi trong phòng",
    usage="Dép khách sạn cung cấp sẵn trong phòng.",
    example_ru="床边有拖鞋。", example_vi="Có dép để cạnh giường."),
503: dict(ru="吹风机", phonetic="chuī fēng jī", pos="n", meaning="máy sấy tóc",
    usage="Thiết bị có sẵn trong phòng khách sạn.",
    example_ru="房间里有吹风机吗？", example_vi="Trong phòng có máy sấy tóc không?"),
602: dict(ru="百货商店", phonetic="bǎi huò shāng diàn", pos="phrase", meaning="cửa hàng bách hóa",
    usage="Cửa hàng lớn bán nhiều loại hàng hóa.",
    example_ru="市中心有一家百货商店。", example_vi="Ở trung tâm có một cửa hàng bách hóa."),
603: dict(ru="大卖场", phonetic="dà mài chǎng", pos="n", meaning="đại siêu thị",
    usage="Siêu thị quy mô rất lớn.",
    example_ru="大卖场东西比较全。", example_vi="Đại siêu thị có đủ loại hàng hơn."),
605: dict(ru="杂货店", phonetic="zá huò diàn", pos="n", meaning="cửa hàng tạp hóa",
    usage="Cửa hàng nhỏ bán đồ dùng hàng ngày.",
    example_ru="巷子口有一家杂货店。", example_vi="Ở đầu ngõ có một cửa hàng tạp hóa."),
608: dict(ru="清仓", phonetic="qīng cāng", pos="v", meaning="xả hàng, thanh lý",
    usage="Chương trình giảm giá để xả hàng tồn.",
    example_ru="这家店在清仓大甩卖。", example_vi="Cửa hàng này đang xả hàng giảm giá lớn."),
610: dict(ru="转账", phonetic="zhuǎn zhàng", pos="v", meaning="chuyển khoản",
    usage="Hình thức thanh toán qua chuyển khoản ngân hàng.",
    example_ru="可以转账付款吗？", example_vi="Có thể thanh toán bằng chuyển khoản không?"),
612: dict(ru="储蓄卡", phonetic="chǔ xù kǎ", pos="n", meaning="thẻ ghi nợ (debit card)",
    usage="Thẻ ngân hàng dùng để rút/thanh toán trực tiếp từ tài khoản.",
    example_ru="我可以用储蓄卡付款吗？", example_vi="Tôi có thể thanh toán bằng thẻ ghi nợ không?"),
614: dict(ru="凭证", phonetic="píng zhèng", pos="n", meaning="chứng từ, biên nhận",
    usage="Giấy tờ chứng minh giao dịch/thanh toán.",
    example_ru="请保留这张凭证。", example_vi="Hãy giữ lại chứng từ này."),
617: dict(ru="分期付款", phonetic="fēn qī fù kuǎn", pos="phrase", meaning="trả góp",
    usage="Hình thức thanh toán trả góp nhiều lần.",
    example_ru="可以分期付款吗？", example_vi="Có thể trả góp không?"),
623: dict(ru="包邮", phonetic="bāo yóu", pos="v", meaning="miễn phí vận chuyển",
    usage="Mua hàng online không mất phí ship.",
    example_ru="这个产品包邮。", example_vi="Sản phẩm này được miễn phí vận chuyển."),
625: dict(ru="议价", phonetic="yì jià", pos="v", meaning="mặc cả, thương lượng giá",
    usage="Mặc cả giá khi mua hàng ở chợ.",
    example_ru="在这里可以议价。", example_vi="Ở đây có thể mặc cả."),
626: dict(ru="批发", phonetic="pī fā", pos="v", meaning="bán buôn, bán sỉ",
    usage="Mua với số lượng lớn giá rẻ hơn.",
    example_ru="这里可以批发买。", example_vi="Ở đây có thể mua sỉ."),
629: dict(ru="促销员", phonetic="cù xiāo yuán", pos="n", meaning="nhân viên khuyến mãi/giới thiệu sản phẩm",
    usage="Nhân viên giới thiệu/bán sản phẩm khuyến mãi tại cửa hàng.",
    example_ru="促销员在推荐新产品。", example_vi="Nhân viên khuyến mãi đang giới thiệu sản phẩm mới."),
650: dict(ru="会员", phonetic="huì yuán", pos="n", meaning="hội viên, thành viên",
    usage="Người đăng ký làm thành viên của cửa hàng/dịch vụ.",
    example_ru="您是会员吗？", example_vi="Bạn có phải là hội viên không?"),
655: dict(ru="汇款", phonetic="huì kuǎn", pos="v", meaning="chuyển tiền (quốc tế/ngân hàng)",
    usage="Gửi tiền qua ngân hàng đến người khác.",
    example_ru="我需要汇款到国外。", example_vi="Tôi cần chuyển tiền ra nước ngoài."),
661: dict(ru="结算", phonetic="jié suàn", pos="v", meaning="thanh toán, quyết toán",
    usage="Quá trình tính tổng và thanh toán.",
    example_ru="我们现在结算吧。", example_vi="Chúng ta thanh toán bây giờ nhé."),
671: dict(ru="航站楼", phonetic="háng zhàn lóu", pos="n", meaning="nhà ga sân bay (terminal)",
    usage="Khu vực nhà ga cụ thể trong sân bay lớn.",
    example_ru="国际航班在T3航站楼。", example_vi="Chuyến bay quốc tế ở nhà ga T3."),
672: dict(ru="签证官", phonetic="qiān zhèng guān", pos="n", meaning="nhân viên xét duyệt visa",
    usage="Người phụ trách kiểm tra/xét duyệt visa tại cửa khẩu.",
    example_ru="签证官检查了我的材料。", example_vi="Nhân viên xét duyệt visa đã kiểm tra hồ sơ của tôi."),
675: dict(ru="行李车", phonetic="xíng li chē", pos="n", meaning="xe đẩy hành lý",
    usage="Xe đẩy dùng để chở hành lý ở sân bay.",
    example_ru="哪里可以找到行李车？", example_vi="Có thể tìm xe đẩy hành lý ở đâu?"),
676: dict(ru="行李标签", phonetic="xíng li biāo qiān", pos="n", meaning="thẻ hành lý",
    usage="Thẻ dán lên vali để nhận diện.",
    example_ru="请贴上行李标签。", example_vi="Hãy dán thẻ hành lý vào."),
677: dict(ru="值机柜台", phonetic="zhí jī guì tái", pos="n", meaning="quầy làm thủ tục check-in",
    usage="Quầy để làm thủ tục check-in ở sân bay.",
    example_ru="值机柜台在哪里？", example_vi="Quầy check-in ở đâu?"),
678: dict(ru="安检口", phonetic="ān jiǎn kǒu", pos="n", meaning="cửa kiểm tra an ninh",
    usage="Nơi hành khách qua kiểm tra an ninh.",
    example_ru="请到三号安检口。", example_vi="Hãy đến cửa kiểm tra an ninh số 3."),
681: dict(ru="安检员", phonetic="ān jiǎn yuán", pos="n", meaning="nhân viên an ninh sân bay",
    usage="Người kiểm tra an ninh tại sân bay.",
    example_ru="安检员检查了我的包。", example_vi="Nhân viên an ninh đã kiểm tra túi của tôi."),
684: dict(ru="优先登机", phonetic="yōu xiān dēng jī", pos="phrase", meaning="lên máy bay ưu tiên",
    usage="Dành cho hành khách hạng thương gia hoặc có trẻ nhỏ.",
    example_ru="商务舱可以优先登机。", example_vi="Hạng thương gia được lên máy bay ưu tiên."),
687: dict(ru="航班信息", phonetic="háng bān xìn xī", pos="phrase", meaning="thông tin chuyến bay",
    usage="Thông tin hiển thị trên bảng điện tử về chuyến bay.",
    example_ru="请查看航班信息屏幕。", example_vi="Hãy xem màn hình thông tin chuyến bay."),
689: dict(ru="电子机票", phonetic="diàn zǐ jī piào", pos="phrase", meaning="vé máy bay điện tử",
    usage="Vé máy bay dạng điện tử, không cần in giấy.",
    example_ru="我用的是电子机票。", example_vi="Tôi dùng vé máy bay điện tử."),
692: dict(ru="过境", phonetic="guò jìng", pos="v", meaning="quá cảnh, đi qua biên giới",
    usage="Đi qua/quá cảnh qua một quốc gia khác.",
    example_ru="我们需要在莫斯科过境。", example_vi="Chúng tôi cần quá cảnh ở Moscow."),
693: dict(ru="航班取消", phonetic="háng bān qǔ xiāo", pos="phrase", meaning="hủy chuyến bay",
    usage="Thông báo hủy chuyến bay.",
    example_ru="航班取消了，请重新安排。", example_vi="Chuyến bay đã bị hủy, vui lòng sắp xếp lại."),
694: dict(ru="改签", phonetic="gǎi qiān", pos="v", meaning="đổi vé/đổi chuyến",
    usage="Đổi sang chuyến bay/vé khác.",
    example_ru="我想改签这张机票。", example_vi="Tôi muốn đổi vé máy bay này."),
708: dict(ru="起飞时间", phonetic="qǐ fēi shí jiān", pos="phrase", meaning="giờ cất cánh",
    usage="Thời điểm máy bay cất cánh.",
    example_ru="起飞时间是几点？", example_vi="Giờ cất cánh là mấy giờ?"),
709: dict(ru="到达时间", phonetic="dào dá shí jiān", pos="phrase", meaning="giờ hạ cánh/đến nơi",
    usage="Thời điểm máy bay hạ cánh/đến nơi.",
    example_ru="到达时间会有变化吗？", example_vi="Giờ đến nơi có thay đổi không?"),
710: dict(ru="始发地", phonetic="shǐ fā dì", pos="n", meaning="điểm xuất phát",
    usage="Nơi bắt đầu hành trình/chuyến bay.",
    example_ru="这趟航班的始发地是北京。", example_vi="Điểm xuất phát của chuyến bay này là Bắc Kinh."),
711: dict(ru="紧急出口", phonetic="jǐn jí chū kǒu", pos="phrase", meaning="cửa thoát hiểm",
    usage="Vị trí cửa thoát hiểm trên máy bay.",
    example_ru="紧急出口在您旁边。", example_vi="Cửa thoát hiểm ở ngay cạnh bạn."),
716: dict(ru="机组人员", phonetic="jī zǔ rén yuán", pos="phrase", meaning="phi hành đoàn",
    usage="Toàn bộ tổ bay gồm phi công và tiếp viên.",
    example_ru="机组人员欢迎大家登机。", example_vi="Phi hành đoàn chào đón mọi người lên máy bay."),
720: dict(ru="中转柜台", phonetic="zhōng zhuǎn guì tái", pos="phrase", meaning="quầy trung chuyển/nối chuyến",
    usage="Quầy hỗ trợ hành khách nối chuyến bay.",
    example_ru="请到中转柜台咨询。", example_vi="Hãy đến quầy trung chuyển để hỏi."),
764: dict(ru="全科医生", phonetic="quán kē yī shēng", pos="phrase", meaning="bác sĩ đa khoa",
    usage="Bác sĩ khám tổng quát đầu tiên.",
    example_ru="先去看全科医生。", example_vi="Trước tiên hãy đi khám bác sĩ đa khoa."),
765: dict(ru="护士站", phonetic="hù shi zhàn", pos="n", meaning="trạm/quầy y tá tại bệnh viện",
    usage="Nơi y tá trực tại bệnh viện.",
    example_ru="护士站在走廊尽头。", example_vi="Trạm y tá ở cuối hành lang."),
767: dict(ru="住院部", phonetic="zhù yuàn bù", pos="n", meaning="khoa nội trú",
    usage="Khu vực bệnh nhân nằm điều trị nội trú.",
    example_ru="他在住院部。", example_vi="Anh ấy đang ở khoa nội trú."),
854: dict(ru="报价单", phonetic="bào jià dān", pos="phrase", meaning="bản báo giá",
    usage="Bản báo giá gửi cho khách hàng/đối tác.",
    example_ru="请发一份报价单给我们。", example_vi="Vui lòng gửi cho chúng tôi bản báo giá."),
855: dict(ru="预付款", phonetic="yù fù kuǎn", pos="n", meaning="tiền đặt cọc, trả trước",
    usage="Khoản tiền trả trước khi ký hợp đồng.",
    example_ru="需要支付百分之五十的预付款。", example_vi="Cần trả trước 50% tiền đặt cọc."),
857: dict(ru="总监", phonetic="zǒng jiān", pos="n", meaning="giám đốc (cấp cao, phụ trách một mảng)",
    usage="Chức danh quản lý cấp cao phụ trách một bộ phận.",
    example_ru="市场总监会参加会议。", example_vi="Giám đốc marketing sẽ tham dự cuộc họp."),
858: dict(ru="下属", phonetic="xià shǔ", pos="n", meaning="cấp dưới",
    usage="Người làm việc dưới quyền quản lý của mình.",
    example_ru="他有几个下属。", example_vi="Anh ấy có vài nhân viên cấp dưới."),
870: dict(ru="创始人", phonetic="chuàng shǐ rén", pos="n", meaning="người sáng lập",
    usage="Người sáng lập ra công ty.",
    example_ru="他是这家公司的创始人。", example_vi="Anh ấy là người sáng lập công ty này."),
871: dict(ru="实习生", phonetic="shí xí shēng", pos="n", meaning="thực tập sinh",
    usage="Nhân viên đang thực tập tại công ty.",
    example_ru="我们今年有两个实习生。", example_vi="Năm nay chúng tôi có hai thực tập sinh."),
882: dict(ru="竞争对手", phonetic="jìng zhēng duì shǒu", pos="n", meaning="đối thủ cạnh tranh",
    usage="Công ty đối thủ trên thị trường.",
    example_ru="我们的竞争对手降价了。", example_vi="Đối thủ cạnh tranh của chúng tôi đã giảm giá."),
912: dict(ru="合同条款", phonetic="hé tong tiáo kuǎn", pos="phrase", meaning="điều khoản hợp đồng",
    usage="Các điều khoản cụ thể trong hợp đồng.",
    example_ru="请仔细阅读合同条款。", example_vi="Hãy đọc kỹ các điều khoản hợp đồng."),
962: dict(ru="细心", phonetic="xì xīn", pos="adj", meaning="tỉ mỉ, cẩn thận",
    usage="Khen ai đó làm việc tỉ mỉ, cẩn thận.",
    example_ru="她做事很细心。", example_vi="Cô ấy làm việc rất tỉ mỉ."),
970: dict(ru="耐心", phonetic="nài xīn", pos="adj", meaning="kiên nhẫn",
    usage="Khen ai đó kiên nhẫn.",
    example_ru="老师对学生很耐心。", example_vi="Giáo viên rất kiên nhẫn với học sinh."),
971: dict(ru="可靠", phonetic="kě kào", pos="adj", meaning="đáng tin cậy",
    usage="Khen ai đó đáng tin cậy.",
    example_ru="他是一个可靠的伙伴。", example_vi="Anh ấy là một đối tác đáng tin cậy."),
972: dict(ru="有礼貌", phonetic="yǒu lǐ mào", pos="phrase", meaning="lịch sự, có lễ độ",
    usage="Khen ai đó cư xử lịch sự.",
    example_ru="服务员很有礼貌。", example_vi="Nhân viên phục vụ rất lịch sự."),
986: dict(ru="谦虚", phonetic="qiān xū", pos="adj", meaning="khiêm tốn",
    usage="Khen ai đó khiêm tốn.",
    example_ru="他很谦虚，从不炫耀。", example_vi="Anh ấy rất khiêm tốn, không bao giờ khoe khoang."),
992: dict(ru="大方", phonetic="dà fang", pos="adj", meaning="hào phóng, rộng rãi",
    usage="Khen ai đó hào phóng.",
    example_ru="谢谢，你真大方。", example_vi="Cảm ơn, bạn thật hào phóng."),
993: dict(ru="好奇", phonetic="hào qí", pos="adj", meaning="tò mò",
    usage="Diễn tả tính hay tò mò.",
    example_ru="孩子们对什么都好奇。", example_vi="Trẻ con tò mò với mọi thứ."),
}

SENT_PATCH = {
523: dict(ru="可以再加一份米饭吗？", phonetic="kě yǐ zài jiā yī fèn mǐ fàn ma？",
    meaning="Cho tôi thêm một phần cơm được không?",
    note="Gọi thêm cơm/món trong lúc ăn tại nhà hàng."),
}

def patch_kind(kind, patch, id_to_chunk):
    changed_files = set()
    for iid, fields in patch.items():
        chunk = id_to_chunk(iid)
        path = os.path.join(ROOT, chunk)
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        found = False
        for it in data:
            if it["id"] == iid:
                for k, v in fields.items():
                    it[k] = v
                found = True
                break
        if not found:
            raise SystemExit(f"id {iid} not found in {chunk}")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=None)
        changed_files.add(chunk)
    print(f"{kind}: patched {len(patch)} ids across files {sorted(changed_files)}")

def word_chunk(iid):
    return f"words_{(iid - 1) // 200 + 1}.json"

def sent_chunk(iid):
    return f"sentences_{(iid - 1) // 200 + 1}.json"

patch_kind("words", WORD_PATCH, word_chunk)
patch_kind("sentences", SENT_PATCH, sent_chunk)
print("Done.")
