#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Round 1: thay các mục 'ru' bị trùng trong gói tiếng Pháp, giữ nguyên id/category."""
import json, os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fr")

WORD_PATCH = {
330: dict(ru="la recette", phonetic="la rhơ-SET", pos="n", meaning="công thức nấu ăn",
    usage="Hướng dẫn cách chế biến món ăn.",
    example_ru="Cette recette est facile à suivre.", example_vi="Công thức này dễ làm theo."),
331: dict(ru="grignoter", phonetic="gri-nyo-TAY", pos="v", meaning="ăn vặt, nhấm nháp",
    usage="Ăn nhẹ giữa các bữa chính.",
    example_ru="J'aime grignoter l'après-midi.", example_vi="Tôi thích ăn vặt vào buổi chiều."),
332: dict(ru="goûter", phonetic="goo-TAY", pos="v", meaning="nếm thử",
    usage="Nếm thử món ăn/đồ uống.",
    example_ru="Vous pouvez goûter avant d'acheter.", example_vi="Bạn có thể nếm thử trước khi mua."),
416: dict(ru="la carte grise", phonetic="la kart GRIZ", pos="phrase", meaning="giấy đăng ký xe",
    usage="Giấy tờ xe cần có khi thuê/lái ô tô ở Pháp.",
    example_ru="N'oubliez pas la carte grise.", example_vi="Đừng quên giấy đăng ký xe."),
435: dict(ru="le scooter", phonetic="lơ sku-TAIR", pos="n", meaning="xe scooter/tay ga",
    usage="Phương tiện phổ biến để di chuyển trong thành phố Pháp.",
    example_ru="Il se déplace en scooter.", example_vi="Anh ấy di chuyển bằng xe scooter."),
464: dict(ru="les phares", phonetic="lay FAR", pos="n", meaning="đèn pha xe",
    usage="Đèn chiếu sáng phía trước xe.",
    example_ru="Allumez les phares la nuit.", example_vi="Hãy bật đèn pha vào ban đêm."),
484: dict(ru="le peignoir", phonetic="lơ pen-NYWAR", pos="n", meaning="áo choàng tắm",
    usage="Áo choàng dùng trong phòng khách sạn sau khi tắm.",
    example_ru="Le peignoir est dans la salle de bain.", example_vi="Áo choàng tắm ở trong phòng tắm."),
488: dict(ru="la vue sur la ville", phonetic="la VUY suhr la VEEL", pos="phrase", meaning="tầm nhìn ra thành phố",
    usage="Mô tả loại phòng khách sạn có tầm nhìn ra thành phố.",
    example_ru="Je préfère une chambre avec vue sur la ville.", example_vi="Tôi thích phòng có tầm nhìn ra thành phố hơn."),
508: dict(ru="accueillir", phonetic="a-kơ-YEER", pos="v", meaning="đón tiếp, chào đón",
    usage="Đón tiếp khách tại khách sạn/công ty.",
    example_ru="L'hôtel accueille les clients 24h/24.", example_vi="Khách sạn đón tiếp khách 24/24."),
510: dict(ru="prolonger", phonetic="pro-lon-ZHAY", pos="v", meaning="gia hạn, kéo dài (thời gian lưu trú)",
    usage="Gia hạn thời gian ở khách sạn.",
    example_ru="Je voudrais prolonger mon séjour.", example_vi="Tôi muốn gia hạn thời gian lưu trú."),
542: dict(ru="longer", phonetic="lon-ZHAY", pos="v", meaning="đi dọc theo",
    usage="Đi dọc theo một con đường/con phố.",
    example_ru="Longez cette rue jusqu'au bout.", example_vi="Hãy đi dọc theo con phố này đến cuối."),
569: dict(ru="l'épicerie", phonetic="lay-pee-SREE", pos="n", meaning="cửa hàng tạp hóa",
    usage="Cửa hàng nhỏ bán đồ ăn hàng ngày.",
    example_ru="Il y a une épicerie au coin de la rue.", example_vi="Có một cửa hàng tạp hóa ở góc phố."),
570: dict(ru="le kiosque", phonetic="lơ kee-OSK", pos="n", meaning="quầy báo/ki-ốt",
    usage="Quầy nhỏ bán báo, đồ lặt vặt trên phố.",
    example_ru="Achetez un journal au kiosque.", example_vi="Hãy mua báo ở quầy ki-ốt."),
613: dict(ru="le rabais", phonetic="lơ ra-BAY", pos="n", meaning="khoản giảm giá",
    usage="Khoản tiền được giảm khi mua hàng.",
    example_ru="Vous avez droit à un rabais de dix pour cent.", example_vi="Bạn được giảm giá mười phần trăm."),
615: dict(ru="la petite monnaie", phonetic="la puh-TEET mo-NAY", pos="phrase", meaning="tiền lẻ",
    usage="Tiền xu/tiền lẻ.",
    example_ru="Avez-vous de la petite monnaie?", example_vi="Bạn có tiền lẻ không?"),
616: dict(ru="l'emballage", phonetic="lom-ba-LAZH", pos="n", meaning="bao bì, đóng gói",
    usage="Bao bì đóng gói sản phẩm.",
    example_ru="L'emballage est abîmé.", example_vi="Bao bì bị hỏng."),
622: dict(ru="l'hypermarché", phonetic="lee-pair-mar-SHAY", pos="n", meaning="đại siêu thị",
    usage="Siêu thị quy mô rất lớn.",
    example_ru="L'hypermarché est en dehors de la ville.", example_vi="Đại siêu thị nằm ở ngoại ô."),
625: dict(ru="le grand magasin", phonetic="lơ grã~ ma-ga-ZÃ~", pos="phrase", meaning="cửa hàng bách hóa lớn",
    usage="Cửa hàng lớn bán nhiều loại hàng hóa.",
    example_ru="Il y a un grand magasin au centre-ville.", example_vi="Có một cửa hàng bách hóa lớn ở trung tâm."),
626: dict(ru="marchander", phonetic="mar-shã~-DAY", pos="v", meaning="mặc cả, trả giá",
    usage="Mặc cả giá khi mua hàng ở chợ.",
    example_ru="On peut marchander sur le marché.", example_vi="Có thể mặc cả ở chợ."),
627: dict(ru="rendre", phonetic="RÃ~-drơ", pos="v", meaning="trả lại (hàng/tiền thừa)",
    usage="Trả lại hàng hoặc tiền thừa.",
    example_ru="Je voudrais rendre cet article.", example_vi="Tôi muốn trả lại món hàng này."),
628: dict(ru="économiser", phonetic="ay-ko-no-mee-ZAY", pos="v", meaning="tiết kiệm",
    usage="Tiết kiệm tiền khi mua sắm.",
    example_ru="J'économise pour mon voyage.", example_vi="Tôi đang tiết kiệm cho chuyến đi của mình."),
629: dict(ru="valoir", phonetic="va-LWAR", pos="v", meaning="đáng giá, có giá trị",
    usage="Diễn tả giá trị của một món đồ.",
    example_ru="Ça vaut vraiment le prix.", example_vi="Nó thực sự đáng giá tiền đó."),
630: dict(ru="convenir", phonetic="kon-vơ-NEER", pos="v", meaning="phù hợp, vừa vặn",
    usage="Diễn tả sự phù hợp (kích cỡ, thời gian...).",
    example_ru="Cette taille me convient parfaitement.", example_vi="Kích cỡ này vừa vặn hoàn hảo với tôi."),
633: dict(ru="le bon d'achat", phonetic="lơ bõ~ da-SHAT", pos="phrase", meaning="phiếu mua hàng",
    usage="Phiếu có giá trị dùng để mua hàng, thường là quà tặng.",
    example_ru="J'ai reçu un bon d'achat pour mon anniversaire.", example_vi="Tôi nhận được phiếu mua hàng nhân sinh nhật."),
661: dict(ru="l'étiquette de prix", phonetic="lay-tee-KET dơ PRI", pos="phrase", meaning="nhãn giá",
    usage="Nhãn ghi giá gắn trên sản phẩm.",
    example_ru="Regardez l'étiquette de prix d'abord.", example_vi="Hãy xem nhãn giá trước."),
671: dict(ru="la file d'attente", phonetic="la feel da-TÃ~T", pos="phrase", meaning="hàng đợi, xếp hàng",
    usage="Hàng người xếp hàng chờ đến lượt (ở sân bay/hải quan).",
    example_ru="La file d'attente est très longue.", example_vi="Hàng đợi rất dài."),
673: dict(ru="la déclaration en douane", phonetic="la day-kla-ra-SYÕ~ ã~ doo-AN", pos="phrase", meaning="tờ khai hải quan",
    usage="Tờ khai khi mang hàng hóa/tiền qua hải quan.",
    example_ru="Remplissez la déclaration en douane.", example_vi="Hãy điền tờ khai hải quan."),
676: dict(ru="le porte-bagages", phonetic="lơ port-ba-GAZH", pos="n", meaning="giá để hành lý",
    usage="Giá/kệ để đặt hành lý (trên xe, tàu).",
    example_ru="Mettez votre sac sur le porte-bagages.", example_vi="Hãy đặt túi của bạn lên giá để hành lý."),
678: dict(ru="le comptoir d'enregistrement", phonetic="lơ kõ~-twar dã~-rjee-strơ-MÃ~", pos="phrase", meaning="quầy làm thủ tục check-in",
    usage="Quầy để làm thủ tục check-in ở sân bay.",
    example_ru="Le comptoir d'enregistrement ferme dans dix minutes.", example_vi="Quầy check-in đóng cửa sau mười phút nữa."),
679: dict(ru="le numéro de vol", phonetic="lơ nyoo-may-RO dơ VOL", pos="phrase", meaning="số hiệu chuyến bay",
    usage="Dùng để tra cứu thông tin chuyến bay.",
    example_ru="Quel est votre numéro de vol?", example_vi="Số hiệu chuyến bay của bạn là gì?"),
680: dict(ru="le décalage horaire", phonetic="lơ day-ka-LAZH o-RAIR", pos="phrase", meaning="lệch múi giờ (jet lag)",
    usage="Hiện tượng mệt mỏi do lệch múi giờ khi bay xa.",
    example_ru="J'ai le décalage horaire après ce vol.", example_vi="Tôi bị lệch múi giờ sau chuyến bay này."),
681: dict(ru="la piste d'atterrissage", phonetic="la peest da-tay-ree-SAZH", pos="phrase", meaning="đường băng",
    usage="Nơi máy bay cất/hạ cánh.",
    example_ru="L'avion est sur la piste d'atterrissage.", example_vi="Máy bay đang ở trên đường băng."),
686: dict(ru="patienter", phonetic="pa-syã~-TAY", pos="v", meaning="kiên nhẫn chờ đợi",
    usage="Chờ đợi một cách kiên nhẫn (ở sân bay, hàng đợi).",
    example_ru="Merci de patienter quelques minutes.", example_vi="Xin vui lòng chờ trong vài phút."),
687: dict(ru="récupérer les bagages", phonetic="ray-kyoo-pay-RAY lay ba-GAZH", pos="phrase", meaning="nhận hành lý",
    usage="Lấy hành lý sau khi máy bay hạ cánh.",
    example_ru="Où peut-on récupérer les bagages?", example_vi="Có thể nhận hành lý ở đâu?"),
689: dict(ru="le copilote", phonetic="lơ ko-pee-LOT", pos="n", meaning="phi công phụ",
    usage="Người hỗ trợ phi công chính điều khiển máy bay.",
    example_ru="Le copilote a géré l'atterrissage.", example_vi="Phi công phụ đã xử lý việc hạ cánh."),
693: dict(ru="l'annulation de vol", phonetic="la-nyoo-la-SYÕ~ dơ VOL", pos="phrase", meaning="sự hủy chuyến bay",
    usage="Thông báo hủy chuyến bay.",
    example_ru="Il y a eu une annulation de vol ce matin.", example_vi="Sáng nay có một chuyến bay bị hủy."),
696: dict(ru="le temps d'escale", phonetic="lơ tã~ des-KAL", pos="phrase", meaning="thời gian quá cảnh",
    usage="Khoảng thời gian dừng chân giữa hai chuyến bay nối tiếp.",
    example_ru="Le temps d'escale est de deux heures.", example_vi="Thời gian quá cảnh là hai tiếng."),
697: dict(ru="le compartiment à bagages", phonetic="lơ kõ~-par-tee-MÃ~ a ba-GAZH", pos="phrase", meaning="khoang hành lý trên đầu (máy bay)",
    usage="Khoang chứa hành lý trên đầu ghế máy bay.",
    example_ru="Rangez votre sac dans le compartiment à bagages.", example_vi="Hãy để túi của bạn vào khoang hành lý trên đầu."),
705: dict(ru="le siège côté couloir", phonetic="lơ syezh ko-TAY koo-LWAR", pos="phrase", meaning="ghế cạnh lối đi",
    usage="Chỗ ngồi cạnh lối đi trên máy bay.",
    example_ru="Je préfère un siège côté couloir.", example_vi="Tôi thích ghế cạnh lối đi hơn."),
761: dict(ru="le généraliste", phonetic="lơ zhay-nay-ra-LEEST", pos="n", meaning="bác sĩ đa khoa",
    usage="Bác sĩ khám tổng quát đầu tiên.",
    example_ru="Il faut d'abord voir le généraliste.", example_vi="Trước tiên cần khám bác sĩ đa khoa."),
763: dict(ru="les urgences", phonetic="lay zoor-ZHÃ~S", pos="n", meaning="khoa cấp cứu",
    usage="Khoa cấp cứu tại bệnh viện.",
    example_ru="Il faut aller aux urgences.", example_vi="Cần phải đến khoa cấp cứu."),
781: dict(ru="le certificat médical", phonetic="lơ sair-tee-fee-KA may-dee-KAL", pos="phrase", meaning="giấy chứng nhận y tế",
    usage="Giấy xác nhận tình trạng sức khỏe từ bác sĩ.",
    example_ru="J'ai besoin d'un certificat médical.", example_vi="Tôi cần giấy chứng nhận y tế."),
834: dict(ru="la canicule", phonetic="la ka-nee-KUYL", pos="n", meaning="đợt nắng nóng gay gắt",
    usage="Thời tiết nắng nóng cực độ kéo dài.",
    example_ru="Il y a une canicule cette semaine.", example_vi="Tuần này có đợt nắng nóng gay gắt."),
854: dict(ru="le devis", phonetic="lơ dơ-VEE", pos="n", meaning="bản báo giá",
    usage="Bản báo giá gửi cho khách hàng/đối tác trước khi ký hợp đồng.",
    example_ru="Pouvez-vous nous envoyer un devis?", example_vi="Bạn có thể gửi cho chúng tôi bản báo giá không?"),
858: dict(ru="le subordonné", phonetic="lơ syoo-bor-do-NAY", pos="n", meaning="cấp dưới, nhân viên cấp dưới",
    usage="Người làm việc dưới quyền quản lý của mình.",
    example_ru="Il a plusieurs subordonnés.", example_vi="Anh ấy có vài nhân viên cấp dưới."),
864: dict(ru="l'agenda", phonetic="la-zhã~-DA", pos="n", meaning="sổ lịch làm việc, lịch hẹn",
    usage="Dùng để ghi lịch làm việc/cuộc hẹn.",
    example_ru="Vérifiez votre agenda pour demain.", example_vi="Hãy kiểm tra lịch làm việc của bạn cho ngày mai."),
866: dict(ru="le stagiaire", phonetic="lơ sta-ZHYAIR", pos="n", meaning="thực tập sinh",
    usage="Nhân viên đang thực tập tại công ty.",
    example_ru="Nous avons deux stagiaires cet été.", example_vi="Chúng tôi có hai thực tập sinh mùa hè này."),
876: dict(ru="la part de marché", phonetic="la par dơ mar-SHAY", pos="phrase", meaning="thị phần",
    usage="Tỷ lệ phần trăm thị trường mà công ty chiếm giữ.",
    example_ru="Notre part de marché a augmenté.", example_vi="Thị phần của chúng tôi đã tăng."),
881: dict(ru="la note de service", phonetic="la not dơ sair-VEES", pos="phrase", meaning="thông báo nội bộ, bản ghi nhớ",
    usage="Văn bản thông báo ngắn trong nội bộ công ty.",
    example_ru="Merci de lire la note de service.", example_vi="Vui lòng đọc thông báo nội bộ."),
887: dict(ru="l'augmentation de salaire", phonetic="log-mã~-ta-SYÕ~ dơ sa-LAIR", pos="phrase", meaning="tăng lương",
    usage="Việc tăng lương cho nhân viên.",
    example_ru="J'ai eu une augmentation de salaire.", example_vi="Tôi đã được tăng lương."),
909: dict(ru="la clientèle", phonetic="la klee-ã~-TEL", pos="n", meaning="lượng khách hàng, tệp khách hàng",
    usage="Tập hợp khách hàng của một doanh nghiệp.",
    example_ru="Notre clientèle a doublé cette année.", example_vi="Lượng khách hàng của chúng tôi đã tăng gấp đôi năm nay."),
911: dict(ru="le bon de commande", phonetic="lơ bõ~ dơ ko-MÃ~D", pos="phrase", meaning="đơn đặt hàng (văn bản chính thức)",
    usage="Văn bản chính thức đặt mua hàng hóa/dịch vụ.",
    example_ru="Envoyez-nous le bon de commande.", example_vi="Hãy gửi cho chúng tôi đơn đặt hàng."),
912: dict(ru="l'expédition", phonetic="lex-pay-dee-SYÕ~", pos="n", meaning="lô hàng gửi đi",
    usage="Việc gửi hàng hóa đi cho khách hàng.",
    example_ru="L'expédition est arrivée à temps.", example_vi="Lô hàng đã đến đúng giờ."),
913: dict(ru="l'inventaire", phonetic="lã~-vã~-TAIR", pos="n", meaning="kiểm kê hàng hóa",
    usage="Quá trình kiểm đếm hàng hóa trong kho.",
    example_ru="Nous faisons l'inventaire chaque mois.", example_vi="Chúng tôi kiểm kê hàng hóa mỗi tháng."),
914: dict(ru="le contrôle qualité", phonetic="lơ kõ~-trol ka-lee-TAY", pos="phrase", meaning="kiểm soát chất lượng",
    usage="Quy trình kiểm tra chất lượng sản phẩm.",
    example_ru="Le contrôle qualité est très strict.", example_vi="Việc kiểm soát chất lượng rất nghiêm ngặt."),
915: dict(ru="l'investisseur", phonetic="lã~-ves-tee-SUHR", pos="n", meaning="nhà đầu tư",
    usage="Người/tổ chức rót vốn đầu tư vào công ty.",
    example_ru="Nous cherchons un nouvel investisseur.", example_vi="Chúng tôi đang tìm một nhà đầu tư mới."),
945: dict(ru="mignon", phonetic="mee-NYÕ~", pos="adj", meaning="dễ thương, xinh xắn",
    usage="Khen ai đó/cái gì đó dễ thương.",
    example_ru="Ce chat est très mignon.", example_vi="Con mèo này rất dễ thương."),
948: dict(ru="épuisant", phonetic="ay-pyoo-ee-ZÃ~", pos="adj", meaning="gây kiệt sức, mệt lử",
    usage="Diễn tả điều gì đó gây mệt mỏi.",
    example_ru="Ce voyage était épuisant.", example_vi="Chuyến đi này thật mệt mỏi."),
949: dict(ru="fiable", phonetic="fee-ABL", pos="adj", meaning="đáng tin cậy",
    usage="Khen ai đó đáng tin cậy.",
    example_ru="C'est un partenaire fiable.", example_vi="Đó là một đối tác đáng tin cậy."),
957: dict(ru="abordable", phonetic="a-bor-DABL", pos="adj", meaning="vừa túi tiền, phải chăng",
    usage="Khen giá cả hợp lý.",
    example_ru="Les prix ici sont abordables.", example_vi="Giá cả ở đây khá phải chăng."),
960: dict(ru="poli", phonetic="po-LEE", pos="adj", meaning="lịch sự",
    usage="Khen ai đó cư xử lịch sự.",
    example_ru="Le personnel est très poli.", example_vi="Nhân viên rất lịch sự."),
962: dict(ru="ambitieux", phonetic="ã~-bee-SYUH", pos="adj", meaning="đầy tham vọng, có chí tiến thủ",
    usage="Khen ai đó có tham vọng, mục tiêu lớn.",
    example_ru="Elle est très ambitieuse dans sa carrière.", example_vi="Cô ấy rất có chí tiến thủ trong sự nghiệp."),
}

SENT_PATCH = {
983: dict(ru="Nous sommes prêts à signer le contrat aujourd'hui.",
    phonetic="noo som pray a see-nyay lơ kõ~-tra o-zhoor-DWEE.",
    meaning="Chúng tôi sẵn sàng ký hợp đồng hôm nay.",
    note="Dùng khi đàm phán đi đến kết quả cuối cùng, sẵn sàng ký kết."),
}

def patch_kind(kind, patch, id_to_chunk):
    changed_files = set()
    for iid, fields in patch.items():
        chunk = id_to_chunk(iid)
        path = os.path.join(ROOT, chunk)
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        found = False
        for it in data:
            if it["id"] == iid:
                for k, v in fields.items():
                    it[k] = v
                found = True
                break
        if not found:
            raise SystemExit(f"id {iid} not found in {chunk}")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=None)
        changed_files.add(chunk)
    print(f"{kind}: patched {len(patch)} ids across files {sorted(changed_files)}")

def word_chunk(iid):
    return f"words_{(iid - 1) // 200 + 1}.json"

def sent_chunk(iid):
    return f"sentences_{(iid - 1) // 200 + 1}.json"

patch_kind("words", WORD_PATCH, word_chunk)
patch_kind("sentences", SENT_PATCH, sent_chunk)
print("Done.")
