#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Round 1: thay các mục 'ru' bị trùng trong gói tiếng Anh bằng từ/câu mới, giữ nguyên id/category."""
import json, os

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "en")

WORD_PATCH = {
267: dict(ru="beverage", phonetic="BEV-rij", pos="n", meaning="đồ uống (nói chung, trang trọng hơn 'drink')",
    usage="Dùng trong menu/văn viết trang trọng hơn từ 'drink'.",
    example_ru="Please choose a beverage from the menu.", example_vi="Hãy chọn một loại đồ uống từ thực đơn."),
452: dict(ru="depart", phonetic="dih-PART", pos="v", meaning="khởi hành, rời đi",
    usage="Động từ ngược nghĩa với 'arrive', dùng cho tàu xe khởi hành.",
    example_ru="The train will depart in five minutes.", example_vi="Tàu sẽ khởi hành sau năm phút."),
607: dict(ru="afford", phonetic="uh-FORD", pos="v", meaning="đủ khả năng chi trả",
    usage="Diễn tả có đủ tiền để mua/làm gì đó.",
    example_ru="I can't afford this right now.", example_vi="Hiện tại tôi không đủ khả năng mua cái này."),
615: dict(ru="refund", phonetic="REE-fund", pos="n", meaning="hoàn tiền",
    usage="Yêu cầu hoàn tiền khi trả lại hàng.",
    example_ru="Can I get a refund for this?", example_vi="Tôi có thể được hoàn tiền cho món này không?"),
588: dict(ru="crossing", phonetic="CROS-ing", pos="n", meaning="chỗ băng qua đường (vạch kẻ đường)",
    usage="Nơi người đi bộ qua đường an toàn.",
    example_ru="Use the crossing to cross the street.", example_vi="Hãy dùng vạch qua đường để sang đường."),
974: dict(ru="messy", phonetic="MES-ee", pos="adj", meaning="bừa bộn, lộn xộn",
    usage="Trái nghĩa với 'clean/tidy', tả nơi bừa bộn.",
    example_ru="The room looks messy.", example_vi="Căn phòng trông bừa bộn."),
325: dict(ru="chef", phonetic="SHEF", pos="n", meaning="đầu bếp (chuyên nghiệp)",
    usage="Người nấu ăn chuyên nghiệp tại nhà hàng.",
    example_ru="The chef recommends the fish today.", example_vi="Đầu bếp gợi ý món cá hôm nay."),
858: dict(ru="supervisor", phonetic="SOO-per-vy-zer", pos="n", meaning="người giám sát, quản lý trực tiếp",
    usage="Người trực tiếp quản lý công việc của bạn.",
    example_ru="I need to ask my supervisor first.", example_vi="Tôi cần hỏi quản lý trực tiếp của mình trước."),
878: dict(ru="intern", phonetic="IN-turn", pos="n", meaning="thực tập sinh",
    usage="Nhân viên đang thực tập tại công ty.",
    example_ru="We have two interns this summer.", example_vi="Chúng tôi có hai thực tập sinh mùa hè này."),
779: dict(ru="surgeon", phonetic="SUR-jun", pos="n", meaning="bác sĩ phẫu thuật",
    usage="Bác sĩ chuyên thực hiện phẫu thuật.",
    example_ru="The surgeon will operate tomorrow.", example_vi="Bác sĩ phẫu thuật sẽ mổ vào ngày mai."),
780: dict(ru="patient", phonetic="PAY-shent", pos="n", meaning="bệnh nhân",
    usage="Người đang được khám/điều trị.",
    example_ru="The patient is waiting in room three.", example_vi="Bệnh nhân đang đợi ở phòng số ba."),
431: dict(ru="passenger", phonetic="PAS-en-jer", pos="n", meaning="hành khách",
    usage="Người đi trên phương tiện giao thông (không phải người lái).",
    example_ru="There are three passengers in the car.", example_vi="Có ba hành khách trong xe."),
857: dict(ru="executive", phonetic="ig-ZEK-yoo-tiv", pos="n", meaning="giám đốc điều hành, cấp quản lý cao",
    usage="Chức danh cấp cao trong công ty.",
    example_ru="She is a senior executive at the firm.", example_vi="Cô ấy là giám đốc điều hành cấp cao tại công ty."),
957: dict(ru="curious", phonetic="KYOOR-ee-us", pos="adj", meaning="tò mò",
    usage="Diễn tả tính hay tò mò, thích khám phá.",
    example_ru="Kids are naturally curious.", example_vi="Trẻ con vốn dĩ tò mò."),
958: dict(ru="confident", phonetic="KON-fi-dent", pos="adj", meaning="tự tin",
    usage="Diễn tả sự tự tin.",
    example_ru="He seems very confident in meetings.", example_vi="Anh ấy có vẻ rất tự tin trong các cuộc họp."),
998: dict(ru="generous", phonetic="JEN-er-us", pos="adj", meaning="hào phóng, rộng lượng",
    usage="Khen ai đó hào phóng.",
    example_ru="That was very generous of you.", example_vi="Bạn thật hào phóng."),
1000: dict(ru="reliable", phonetic="ri-LY-uh-bul", pos="adj", meaning="đáng tin cậy",
    usage="Khen ai đó đáng tin cậy.",
    example_ru="He's a reliable partner.", example_vi="Anh ấy là một đối tác đáng tin cậy."),
986: dict(ru="exhausted", phonetic="ig-ZAWS-tid", pos="adj", meaning="kiệt sức, rất mệt",
    usage="Diễn tả mệt mỏi cực độ.",
    example_ru="I'm exhausted after the flight.", example_vi="Tôi kiệt sức sau chuyến bay."),
508: dict(ru="voucher", phonetic="VOW-cher", pos="n", meaning="phiếu (giảm giá/dịch vụ)",
    usage="Phiếu đổi dịch vụ/quà tặng tại khách sạn.",
    example_ru="You can use this voucher for breakfast.", example_vi="Bạn có thể dùng phiếu này cho bữa sáng."),
614: dict(ru="warranty", phonetic="WOR-en-tee", pos="n", meaning="bảo hành",
    usage="Giấy bảo hành khi mua đồ điện tử.",
    example_ru="Does this come with a warranty?", example_vi="Sản phẩm này có bảo hành không?"),
917: dict(ru="quotation", phonetic="kwoh-TAY-shun", pos="n", meaning="báo giá",
    usage="Bản báo giá gửi cho khách hàng/đối tác.",
    example_ru="Please send us a quotation.", example_vi="Vui lòng gửi cho chúng tôi bản báo giá."),
996: dict(ru="thirsty", phonetic="THUR-stee", pos="adj", meaning="khát nước",
    usage="Diễn tả cảm giác khát.",
    example_ru="I'm really thirsty.", example_vi="Tôi khát nước quá."),
766: dict(ru="syrup", phonetic="SIR-up", pos="n", meaning="siro thuốc (dạng lỏng)",
    usage="Thuốc dạng siro, thường cho trẻ em.",
    example_ru="Give the child one spoon of syrup.", example_vi="Cho trẻ uống một thìa siro."),
899: dict(ru="memo", phonetic="MEM-oh", pos="n", meaning="bản ghi nhớ, thông báo nội bộ",
    usage="Văn bản thông báo ngắn trong nội bộ công ty.",
    example_ru="Please read the memo before the meeting.", example_vi="Vui lòng đọc bản ghi nhớ trước cuộc họp."),
692: dict(ru="carry-on", phonetic="KAIR-ee-on", pos="n", meaning="hành lý xách tay",
    usage="Hành lý được phép mang lên khoang máy bay.",
    example_ru="Is this bag okay as a carry-on?", example_vi="Túi này có được tính là hành lý xách tay không?"),
620: dict(ru="receipt", phonetic="ri-SEET", pos="n", meaning="hóa đơn/biên lai (giấy)",
    usage="Giữ lại để đổi trả hàng.",
    example_ru="Keep the receipt just in case.", example_vi="Hãy giữ hóa đơn phòng khi cần."),
492: dict(ru="hairdryer", phonetic="HAIR-dry-er", pos="n", meaning="máy sấy tóc",
    usage="Thiết bị có sẵn trong phòng khách sạn.",
    example_ru="Is there a hairdryer in the room?", example_vi="Trong phòng có máy sấy tóc không?"),
634: dict(ru="cart", phonetic="KART", pos="n", meaning="xe đẩy hàng (siêu thị)",
    usage="Dùng khi mua sắm ở siêu thị.",
    example_ru="Grab a cart at the entrance.", example_vi="Hãy lấy xe đẩy ở lối vào."),
683: dict(ru="runway", phonetic="RUN-way", pos="n", meaning="đường băng",
    usage="Nơi máy bay cất/hạ cánh.",
    example_ru="The plane is on the runway now.", example_vi="Máy bay đang ở trên đường băng."),
681: dict(ru="layover", phonetic="LAY-oh-ver", pos="n", meaning="thời gian dừng/quá cảnh giữa hai chuyến bay",
    usage="Khoảng thời gian chờ giữa các chuyến bay nối chuyến.",
    example_ru="We have a two-hour layover in Dubai.", example_vi="Chúng tôi có hai tiếng quá cảnh ở Dubai."),
712: dict(ru="check-in counter", phonetic="CHEK-in KOWN-ter", pos="phrase", meaning="quầy làm thủ tục",
    usage="Nơi làm thủ tục và gửi hành lý.",
    example_ru="The check-in counter opens two hours before departure.", example_vi="Quầy làm thủ tục mở cửa hai tiếng trước giờ bay."),
677: dict(ru="gate number", phonetic="GAYT NUM-ber", pos="phrase", meaning="số cổng ra máy bay",
    usage="Hỏi/xem số cổng để lên máy bay.",
    example_ru="What's the gate number for this flight?", example_vi="Số cổng lên máy bay của chuyến này là bao nhiêu?"),
708: dict(ru="excess baggage", phonetic="ik-SES BAG-ij", pos="phrase", meaning="hành lý quá cân",
    usage="Khi hành lý vượt cân quy định.",
    example_ru="You'll have to pay for excess baggage.", example_vi="Bạn sẽ phải trả thêm phí cho hành lý quá cân."),
709: dict(ru="duty-free", phonetic="DOO-tee-free", pos="adj", meaning="miễn thuế (cửa hàng/hàng hóa)",
    usage="Mua hàng miễn thuế ở sân bay.",
    example_ru="Let's check the duty-free shop.", example_vi="Hãy ghé qua cửa hàng miễn thuế."),
679: dict(ru="immigration", phonetic="im-uh-GRAY-shun", pos="n", meaning="(khu vực) nhập cảnh, xuất nhập cảnh",
    usage="Nơi kiểm tra hộ chiếu khi nhập/xuất cảnh.",
    example_ru="Immigration is on the second floor.", example_vi="Khu vực nhập cảnh ở tầng hai."),
680: dict(ru="visa", phonetic="VEE-zuh", pos="n", meaning="thị thực",
    usage="Giấy phép nhập cảnh vào một quốc gia.",
    example_ru="Do I need a visa to enter Russia?", example_vi="Tôi có cần visa để nhập cảnh Nga không?"),
699: dict(ru="cancellation", phonetic="kan-suh-LAY-shun", pos="n", meaning="sự hủy (chuyến bay)",
    usage="Thông báo hủy chuyến bay.",
    example_ru="There was a cancellation announcement.", example_vi="Có thông báo hủy chuyến."),
674: dict(ru="suitcase", phonetic="SOOT-kays", pos="n", meaning="va li",
    usage="Loại hành lý cứng có bánh xe.",
    example_ru="My suitcase is quite heavy.", example_vi="Va li của tôi khá nặng."),
675: dict(ru="conveyor belt", phonetic="kon-VAY-er BELT", pos="phrase", meaning="băng chuyền (nhận hành lý)",
    usage="Nơi hành lý được đưa ra sau khi hạ cánh.",
    example_ru="Wait by the conveyor belt for your bag.", example_vi="Đợi ở băng chuyền để lấy hành lý."),
684: dict(ru="metal detector", phonetic="MET-ul di-TEK-ter", pos="phrase", meaning="máy dò kim loại",
    usage="Thiết bị an ninh sân bay để kiểm tra.",
    example_ru="Please walk through the metal detector.", example_vi="Vui lòng đi qua máy dò kim loại."),
687: dict(ru="customs declaration", phonetic="KUS-tumz dek-luh-RAY-shun", pos="phrase", meaning="tờ khai hải quan",
    usage="Điền khi mang hàng hóa/tiền qua hải quan.",
    example_ru="Fill out the customs declaration form.", example_vi="Hãy điền vào tờ khai hải quan."),
673: dict(ru="boarding time", phonetic="BOR-ding TYM", pos="phrase", meaning="giờ lên máy bay",
    usage="Thời điểm bắt đầu cho hành khách lên máy bay.",
    example_ru="Boarding time is 10:30.", example_vi="Giờ lên máy bay là 10:30."),
702: dict(ru="overhead bin", phonetic="OH-ver-hed BIN", pos="phrase", meaning="khoang hành lý trên đầu (trên máy bay)",
    usage="Nơi cất hành lý xách tay trên máy bay.",
    example_ru="Put your bag in the overhead bin.", example_vi="Hãy để túi của bạn vào khoang hành lý trên đầu."),
703: dict(ru="seat belt", phonetic="SEET BELT", pos="phrase", meaning="dây an toàn",
    usage="Dây an toàn trên máy bay/ô tô.",
    example_ru="Please fasten your seat belt.", example_vi="Vui lòng thắt dây an toàn."),
698: dict(ru="final call", phonetic="FY-nul KAWL", pos="phrase", meaning="thông báo cuối cùng gọi hành khách lên máy bay",
    usage="Thông báo cuối trước khi đóng cổng ra máy bay.",
    example_ru="This is the final call for flight 202.", example_vi="Đây là thông báo cuối cùng cho chuyến bay 202."),
706: dict(ru="co-pilot", phonetic="KOH-py-lut", pos="n", meaning="phi công phụ",
    usage="Người hỗ trợ phi công chính điều khiển máy bay.",
    example_ru="The co-pilot handled the landing.", example_vi="Phi công phụ đã xử lý việc hạ cánh."),
705: dict(ru="ground staff", phonetic="GROWND STAF", pos="phrase", meaning="nhân viên mặt đất",
    usage="Nhân viên làm việc tại sân bay (không phải trên máy bay).",
    example_ru="Ask the ground staff for help.", example_vi="Hãy hỏi nhân viên mặt đất để được giúp đỡ."),
695: dict(ru="shuttle bus", phonetic="SHUT-ul BUS", pos="phrase", meaning="xe buýt trung chuyển",
    usage="Xe đưa đón giữa các nhà ga/bãi đỗ xe sân bay.",
    example_ru="Take the shuttle bus to terminal two.", example_vi="Hãy đi xe buýt trung chuyển đến nhà ga số hai."),
981: dict(ru="nervous", phonetic="NUR-vus", pos="adj", meaning="lo lắng, hồi hộp",
    usage="Diễn tả cảm giác lo lắng trước sự kiện gì đó.",
    example_ru="I'm a bit nervous about the interview.", example_vi="Tôi hơi lo lắng về buổi phỏng vấn."),
646: dict(ru="installment", phonetic="in-STAWL-ment", pos="n", meaning="trả góp (từng đợt)",
    usage="Hình thức thanh toán trả góp nhiều lần.",
    example_ru="You can pay in installments.", example_vi="Bạn có thể trả góp."),
618: dict(ru="exchange rate", phonetic="iks-CHAYNJ RAYT", pos="phrase", meaning="tỷ giá hối đoái",
    usage="Tỷ lệ quy đổi giữa hai loại tiền tệ.",
    example_ru="What's today's exchange rate?", example_vi="Tỷ giá hôm nay là bao nhiêu?"),
773: dict(ru="prescription", phonetic="pri-SKRIP-shun", pos="n", meaning="đơn thuốc",
    usage="Giấy chỉ định thuốc của bác sĩ.",
    example_ru="You need a prescription for this.", example_vi="Bạn cần đơn thuốc để mua cái này."),
603: dict(ru="checkout", phonetic="CHEK-owt", pos="n", meaning="quầy thanh toán",
    usage="Nơi trả tiền khi mua sắm ở siêu thị.",
    example_ru="The line at the checkout is long.", example_vi="Hàng chờ ở quầy thanh toán dài quá."),
605: dict(ru="price tag", phonetic="PRYS TAG", pos="phrase", meaning="nhãn giá",
    usage="Nhãn ghi giá gắn trên sản phẩm.",
    example_ru="Check the price tag first.", example_vi="Hãy kiểm tra nhãn giá trước."),
911: dict(ru="revenue", phonetic="REV-uh-noo", pos="n", meaning="doanh thu",
    usage="Tổng thu nhập của công ty.",
    example_ru="Revenue increased this quarter.", example_vi="Doanh thu đã tăng trong quý này."),
604: dict(ru="department store", phonetic="di-PART-ment STOR", pos="phrase", meaning="cửa hàng bách hóa",
    usage="Cửa hàng lớn bán nhiều loại hàng hóa.",
    example_ru="There's a department store downtown.", example_vi="Có một cửa hàng bách hóa ở trung tâm."),
882: dict(ru="expense", phonetic="ik-SPENS", pos="n", meaning="chi phí",
    usage="Khoản chi tiêu trong công việc/kinh doanh.",
    example_ru="Please submit your expenses by Friday.", example_vi="Vui lòng nộp bảng chi phí trước thứ Sáu."),
970: dict(ru="affordable", phonetic="uh-FOR-duh-bul", pos="adj", meaning="vừa túi tiền, phải chăng",
    usage="Khen giá cả hợp lý.",
    example_ru="The prices here are affordable.", example_vi="Giá cả ở đây khá phải chăng."),
971: dict(ru="worth it", phonetic="WURTH IT", pos="phrase", meaning="đáng giá, đáng đồng tiền",
    usage="Diễn tả điều gì đó xứng đáng với chi phí bỏ ra.",
    example_ru="It's expensive, but worth it.", example_vi="Nó đắt, nhưng đáng giá."),
869: dict(ru="vendor", phonetic="VEN-der", pos="n", meaning="nhà cung cấp, người bán",
    usage="Đơn vị cung cấp hàng hóa/dịch vụ cho công ty.",
    example_ru="We changed our vendor last month.", example_vi="Chúng tôi đã đổi nhà cung cấp tháng trước."),
854: dict(ru="purchase order", phonetic="PUR-chus OR-der", pos="phrase", meaning="đơn đặt hàng (thương mại)",
    usage="Văn bản chính thức đặt mua hàng hóa/dịch vụ.",
    example_ru="Please send the purchase order first.", example_vi="Vui lòng gửi đơn đặt hàng trước."),
916: dict(ru="shipment", phonetic="SHIP-ment", pos="n", meaning="lô hàng (vận chuyển)",
    usage="Một lô hàng được gửi đi/nhận về.",
    example_ru="The shipment arrived on time.", example_vi="Lô hàng đã đến đúng giờ."),
}

SENT_PATCH = {
727: dict(ru="Which bus goes downtown?", phonetic="wich BUS gohz DOWN-town?",
    meaning="Xe buýt nào đi vào trung tâm thành phố?",
    note="Hỏi khi đứng ở trạm xe buýt, muốn biết tuyến nào đi vào trung tâm."),
819: dict(ru="I need to see a doctor immediately.", phonetic="I need too SEE uh DOK-ter ih-MEE-dee-ut-lee.",
    meaning="Tôi cần gặp bác sĩ ngay lập tức.",
    note="Dùng khi tình trạng sức khỏe khẩn cấp, cần được khám ngay."),
668: dict(ru="Do you have this in a smaller size?", phonetic="doo yoo HAV this in uh SMAWL-er SYZ?",
    meaning="Cửa hàng có size nhỏ hơn không?",
    note="Hỏi khi món đồ hiện tại không vừa, muốn đổi sang size nhỏ hơn."),
}

def patch_kind(kind, patch, id_to_chunk):
    changed_files = set()
    for iid, fields in patch.items():
        chunk = id_to_chunk(iid)
        path = os.path.join(ROOT, chunk)
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        found = False
        for it in data:
            if it["id"] == iid:
                for k, v in fields.items():
                    it[k] = v
                found = True
                break
        if not found:
            raise SystemExit(f"id {iid} not found in {chunk}")
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=None)
        changed_files.add(chunk)
    print(f"{kind}: patched {len(patch)} ids across files {sorted(changed_files)}")

def word_chunk(iid):
    return f"words_{(iid - 1) // 200 + 1}.json"

def sent_chunk(iid):
    return f"sentences_{(iid - 1) // 200 + 1}.json"

patch_kind("words", WORD_PATCH, word_chunk)
patch_kind("sentences", SENT_PATCH, sent_chunk)
print("Done.")
