#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Sửa các thành ngữ ở sentences_7.json (tiếng Anh) bị trùng với đợt 1 (sentences_6.json)."""
import json, os

PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "en", "sentences_7.json")

PATCH = {
1111: dict(ru="cut to the chase", phonetic="kut too thuh CHAYS",
    meaning="đi thẳng vào vấn đề, nói ngắn gọn",
    note="Nghĩa đen 'cắt cảnh rượt đuổi trong phim' — ý nói bỏ qua phần giới thiệu dài dòng, đi thẳng vào trọng tâm."),
1114: dict(ru="back to the grind", phonetic="bak too thuh GRYND",
    meaning="quay lại làm việc (sau kỳ nghỉ)",
    note="'Grind' nghĩa là công việc nhàm chán lặp lại; dùng khi diễn tả quay lại guồng công việc thường ngày."),
1115: dict(ru="raise the bar", phonetic="rayz thuh BAR",
    meaning="nâng cao tiêu chuẩn/kỳ vọng",
    note="Dùng khi ai đó đặt ra tiêu chuẩn cao hơn cho công việc/thành tích."),
1118: dict(ru="keep someone in the loop", phonetic="keep SUM-wun in thuh LOOP",
    meaning="luôn cập nhật thông tin cho ai đó",
    note="Rất hay dùng trong công việc, ví dụ 'Keep me in the loop' = hãy cập nhật cho tôi biết tình hình."),
1121: dict(ru="cover all the bases", phonetic="KUV-er awl thuh BAY-siz",
    meaning="chuẩn bị kỹ lưỡng mọi mặt",
    note="Đảm bảo không bỏ sót khía cạnh nào khi lên kế hoạch."),
1138: dict(ru="on the fence", phonetic="on thuh FENS",
    meaning="lưỡng lự, chưa quyết định",
    note="Nghĩa đen 'ngồi trên hàng rào' — chưa nghiêng về phe nào, còn phân vân."),
1146: dict(ru="read between the lines", phonetic="reed bih-TWEEN thuh LYNZ",
    meaning="hiểu ý ẩn sau lời nói",
    note="Hiểu được điều người khác không nói thẳng ra."),
1147: dict(ru="burn bridges", phonetic="burn BRIJ-iz",
    meaning="cắt đứt quan hệ, tự chặn đường lui",
    note="Hành động khiến không thể quay lại hợp tác/làm hòa được nữa."),
1149: dict(ru="jump through hoops", phonetic="jump throo HOOPS",
    meaning="phải trải qua nhiều thủ tục/khó khăn phức tạp",
    note="Diễn tả việc phải làm nhiều bước rắc rối để đạt được điều gì đó."),
1156: dict(ru="not born yesterday", phonetic="not BORN YES-ter-day",
    meaning="không ngây thơ, không dễ bị lừa",
    note="Khẳng định mình đủ từng trải để không bị lừa gạt."),
1164: dict(ru="off the top of my head", phonetic="of thuh TOP uv my HED",
    meaning="nói ngay không cần suy nghĩ kỹ/không chắc chắn 100%",
    note="Dùng khi trả lời nhanh mà chưa kiểm tra lại thông tin."),
1165: dict(ru="in the same boat", phonetic="in thuh SAYM BOHT",
    meaning="cùng cảnh ngộ, cùng hoàn cảnh khó khăn",
    note="Diễn tả việc nhiều người đang gặp cùng một vấn đề."),
1176: dict(ru="go cold turkey", phonetic="goh KOHLD TUR-kee",
    meaning="bỏ (thói quen/chất gây nghiện) đột ngột hoàn toàn",
    note="Dừng lại ngay lập tức không giảm dần, thường nói về bỏ thuốc lá/rượu."),
1183: dict(ru="come down with something", phonetic="kum DOWN with SUM-thing",
    meaning="bắt đầu bị ốm/mắc bệnh gì đó",
    note="Dùng khi cảm thấy triệu chứng bệnh bắt đầu xuất hiện."),
1185: dict(ru="batten down the hatches", phonetic="BAT-en down thuh HACH-iz",
    meaning="chuẩn bị đối phó với khó khăn sắp tới",
    note="Nghĩa đen là chằng buộc boong tàu trước bão; nghĩa bóng là chuẩn bị ứng phó tình huống xấu."),
1192: dict(ru="few and far between", phonetic="fyoo and FAR bih-TWEEN",
    meaning="hiếm khi xảy ra, thưa thớt",
    note="Diễn tả tần suất rất thấp của một sự việc."),
1197: dict(ru="keep something under wraps", phonetic="keep SUM-thing UN-der RAPS",
    meaning="giữ bí mật, không tiết lộ",
    note="Giữ kín thông tin/kế hoạch cho đến khi công bố chính thức."),
1212: dict(ru="big yikes", phonetic="big YYKS",
    meaning="quá xấu hổ/tệ (thán từ Gen Z)",
    note="Dùng để bình luận về tình huống xấu hổ hoặc lúng túng của ai đó."),
1218: dict(ru="mid", phonetic="MID",
    meaning="tầm tầm, không đặc sắc (tiếng lóng Gen Z)",
    note="Đánh giá điều gì đó chỉ ở mức trung bình, không hay không dở."),
1226: dict(ru="bussin", phonetic="BUS-in",
    meaning="ngon tuyệt (đồ ăn, tiếng lóng rất mới)",
    note="Khen đồ ăn cực kỳ ngon, phổ biến trên mạng xã hội gần đây."),
1227: dict(ru="npc energy", phonetic="EN-pee-SEE EN-er-jee",
    meaning="hành xử vô hồn, thiếu cá tính (tiếng lóng internet)",
    note="Xuất phát từ thuật ngữ game 'NPC' (nhân vật không phải người chơi) — ý chê ai đó phản ứng máy móc, thiếu tư duy riêng."),
1229: dict(ru="delulu", phonetic="dih-LOO-loo",
    meaning="ảo tưởng, mơ mộng viển vông (tiếng lóng internet)",
    note="Viết tắt vui từ 'delusional', thường dùng đùa khi ai đó có suy nghĩ xa rời thực tế."),
1231: dict(ru="doomscrolling", phonetic="DOOM-skroh-ling",
    meaning="lướt mạng xã hội liên tục xem tin xấu",
    note="Thói quen lướt điện thoại xem hết tin tiêu cực này đến tin khác dù biết nó không tốt cho tâm trạng."),
1232: dict(ru="say less", phonetic="say LES",
    meaning="khỏi cần nói thêm, hiểu rồi (đồng ý ngay)",
    note="Dùng để xác nhận đã hiểu và đồng ý mà không cần giải thích thêm."),
1233: dict(ru="understood the assignment", phonetic="un-der-STOOD thee uh-SYN-ment",
    meaning="làm đúng như kỳ vọng, làm rất tốt vai trò của mình",
    note="Khen ai đó thể hiện xuất sắc, đúng 'bài' được giao (thường dùng cho outfit/màn trình diễn)."),
1234: dict(ru="it is what it is", phonetic="it iz WUT it iz",
    meaning="thôi thì cũng đành vậy, chấp nhận thực tế",
    note="Dùng khi chấp nhận một tình huống không thể thay đổi được."),
1237: dict(ru="curiosity killed the cat", phonetic="kyoor-ee-OS-i-tee kild thuh KAT",
    meaning="tò mò quá có thể gặp rắc rối",
    note="Lời cảnh báo nhẹ nhàng khi ai đó tò mò thái quá."),
1247: dict(ru="step up to the plate", phonetic="step UP too thuh PLAYT",
    meaning="đứng ra nhận trách nhiệm, hành động khi cần thiết",
    note="Nghĩa đen từ bóng chày (bước vào vị trí đánh bóng); nghĩa bóng là sẵn sàng gánh vác khi cần."),
}

data = json.load(open(PATH, encoding="utf-8"))
for it in data:
    if it["id"] in PATCH:
        it.update(PATCH[it["id"]])
json.dump(data, open(PATH, "w", encoding="utf-8"), ensure_ascii=False)
print(f"patched {len(PATCH)} ids in {PATH}")
